### ISSUE TITLE
Second Menu Block duplicates on window resize

### ISSUE THREAD

**Issue by ashishpachauriap** [vanjarosoftware/Vanjaro.Platform#1]
I have a page where I added 2 menu blocks. The idea being to have one menu at the top and one in the footer. I noticed that when the browser window is resized, it duplicates the bottom menu block on the page. Here's a quick video showing the bug. When refreshing the page, it doesn't always reset the 2nd menu, so sometimes you'll see duplicate menus on the preview page. 

**https://www.screencast.com/t/Ka4cjXAUiF**

**Comment by joshgk00** [comment]
I also noticed that this is happening when just adding a new page, when there is only 1 menu block defined. In this screencast, it's a fresh install of Alpha 2. The only thing I added was a background image to the existing global block.
https://www.screencast.com/t/3hA9RY14

**Comment by meetmandeep** [comment]
Yes. We're aware of this issue with real-time preview. Refreshing will clear the issue.

We're currently working to resolve this issue and it will be pushed out in Alpha 3.

**Comment by erw13n** [comment]
Also after create a new page, hovering the Bottom Bar will duplicate the Menu multiple time :
![image](https://user-images.githubusercontent.com/792847/77546803-fa56a980-6ede-11ea-8267-8c02a280e1b6.png)

![image](https://user-images.githubusercontent.com/792847/77546829-080c2f00-6edf-11ea-910e-99b29a3c3a3c.png)

**Comment by meetmandeep** [comment]
This issue has been resoled in Alpha 3
