### ISSUE TITLE
Cannot remove or create splash page

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1005]
After the upgrade to RC I cannot delete the splash page. I also cannot find a place to assign a new splash page. I really need help on how to get rid of that splash page.

**Comment by meetmandeep** [comment]
Splash pages are no longer commonly used and hence Vanjaro will not be supporting this feature. 

You can get rid of the Splash Page from all portals by executing the following query in SQL Console

UPDATE PortalLocalization SET SplashTabId = NULL
