### ISSUE TITLE
certain changes don't immediately cascade, causing unexpected results

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#1051]
**Describe the bug**
This will illustrate one way to cause an unexpected behavior. It has aspects in common  with already reported issues I think, so maybe is solved by the upcoming RC2.

**To Reproduce**
Go to an existing page, and then Page Settings for that page. Change the Basic Name of the page and click Update. Go back tp Page Settings and try to change the Basic Name again and you will see that the right-side display is incorrect. 

**Screenshots**
video attached.

https://user-images.githubusercontent.com/8103212/114281909-1a380d00-9a0f-11eb-9ef4-5fe80d7cf63c.mp4

**Comment by meetmandeep** [comment]
Thanks for reporting this. I was able to reproduce this. Changing the page name causes the URL of the page to change. 

We'll resolve this in RC 2.

**Comment by hshimanshusharma** [comment]
@meetmandeep  The issue has been done in RC 2
