### ISSUE TITLE
Site map seems to be incomplete XML file; rejected with error by Google Search

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#1052]
**Describe the bug**
The site map doesn't construct a complete XML file.

**To Reproduce**
Submit the site map to Google Search.

**Expected behavior**
Pages in the site map will be verified and indexed.

**Current behavior**
Google Search response to submitted site map:
Sitemap can be read, but has errors
Missing XML tag
This required tag is missing. Please add it and resubmit.
Line 2
Parent tag: urlset
Tag: url.

**Additional context**

**Comment by meetmandeep** [comment]
This has been reproduced. The individual pages don't have the SiteMap Priority set. For immediate resolution, you can go ahead and set a priority from Page Settings > SEO > Advanced

Otherwise, this will be resolved in RC 2.
