### ISSUE TITLE
URL issue in multi language setup

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#1082]
**Describe the bug**
If you have a page 'for individuals', it gets the url /for-individuals. That's good.
Now you translate it to Dutch (so 2 languages active) and will call the page 'particulieren'. The menu can be translated but the url remains /for-individuals regardless of the chosen language. 

**Expected behavior**
The url corresponds with the active language. 

Vanjaro version RC
DNN 9.9.1

**Comment by meetmandeep** [comment]
> The menu can be translated but the url remains /for-individuals regardless of the chosen language.

The URL can also be translated. Click on Page Settings > SEO and add a new URL for that locale. 

But this should also be automated. Changing the page name should automatically create a matching URL in specific locale and 301 existing URLs. We'll add this feature.

**Comment by Tychodewaard** [comment]
Many thanks! Remark for other who might stumble upon this:
I tried changing the url but that changes the url for all languages. Mandeeps solutions works perfectly. Because the added url gets the 200 status for the chosen locale, it all works.
