### ISSUE TITLE
When Signing out I get a 404 Error

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1179]
**Describe the bug**
When I  Sign out of the website I am redirected to  https://dev.jcesba.org/tabid/0/Default.aspx And I am not signed out.

**To Reproduce**
1. Sign in.
2. Sign out.

**Expected behavior**
I should be redirected to the home page

**Current behavior**
I am redirected to  https://dev.jcesba.org/tabid/0/Default.aspx

**Screenshots**
https://screencast-o-matic.com/watch/crh1I9Vfcgl

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: All

**Comment by meetmandeep** [comment]
Do you have the Sign In Redirect page set? From Site > Pages > In Context Menu (3 Dots) > Set Page As > Show After Logout

Let me know if that resolves the issue?

**Comment by scottw12** [comment]
Yes that was it, I totally missed the new entries there.   Thanks

**Comment by scottw12** [comment]
Closing this issue as solved
