### ISSUE TITLE
Changes to menu appearance don't percolate to the display

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#1182]
**Describe the bug**
Making changes to the Menu : Navigation in Basic Theme settings will preview and save as expected, but once saved, the menu displayed on the page doesn't reflect the changes.

**To Reproduce**
1. Go to Design, Themes, Basic Settings, Site, Menu, Navigation
2. Change font size and font weight
3. Notice the visual changes to the nav menu and click Save Theme
4. Notice how the menu display reverts to the default after the Save Theme action completes

**Expected behavior**
The displayed Theme should reflect the desired changes to the menu.

**Current behavior**
The settings get saved but don't get updated in the theme display.

**Additional context**
Desktop display on Vanjaro RC2.

**Comment by meetmandeep** [comment]
@eswanzey I'm unable to duplicate this. 

- Was this on a new RC 2 or upgraded one? 
- Are you on Vanjaro Platform or Vanjaro for DNN?
- Did you "Enable Debug Mode" or turned off Client Resource Management?

**Comment by eswanzey** [comment]
Upgraded RC 2, Vanjaro Platform, no.

Today, the same attempt was successful. I'll close this with comment and will reopen if I can force it to reoccur.
