### ISSUE TITLE
Upgrade in multi language setup

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#1184]
**Describe the bug**
Upgrading from RC1 to RC2 reset page names and page titles.
The page names translated into Italian were English again. And the page title became blank.

**Comment by Tychodewaard** [comment]
And if you change the title / page name, the original page is redirected too many times so it is not working anymore.

**Comment by meetmandeep** [comment]
@nikhilmandeeps Are you able to reproduce this?

**Comment by meetmandeep** [comment]
> The page names translated into Italian were English again. And the page title became blank.

How were the page names translated to Italian in RC 1? Using Vanjaro interface or DNN? 

> And if you change the title / page name, the original page is redirected too many times so it is not working anymore.

That might be a browser cache issue. Try in Incognito Mode.

**Comment by meetmandeep** [comment]
@Tychodewaard This issue has been confirmed. There were architectural changes to the database that required dropping the Localization table. I'm going to log this as a breaking change in RC 2 notes.
