### ISSUE TITLE
creating new sites sometimes gives white page and error in log

### ISSUE THREAD

**Issue by paulfijma** [vanjarosoftware/Vanjaro.Platform#119]
installed a fully fresh vanjaro - clean install (Vanjaro_Platform_0.5.1_x64_Install)
initial site creation worked. 
wanted to add several sites:  tools > sites > plus_sign
 
When i create a new site it doesn't always work.  it stops at the end of the process and doesn't close the page. 
this happened several times.  it sometimes works. I will upgrade my SQL to speed up, if that eliminates the problem i will addd that as comment. (currnetly using a azure mssql basic 5 dtu (worked fine with 14 regular dnn sites in one install base.))

The error: 
AbsoluteURL /API/Sites/add/create DefaultDataProvider DotNetNuke.Data
AbsoluteURL:/API/Sites/add/create
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:12659a94-81b9-4f54-8be0-313be3bcf885
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:x5WlaGLVxr/2rvK1/cgd6nbpCuc=
Message:Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index
StackTrace:
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) at Vanjaro.UXManager.Extensions.Menu.Sites.Managers.SitesManager.CreatePortal(CreatePortalRequest request)
InnerMessage:
InnerStackTrace:
Source:mscorlib
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: vmixxxxxxx (obfuscated)

**Comment by meetmandeep** [comment]
There is a known issue that would prevent installing extensions, creating new sites, or saving the theme. See #108, #113 

Theme is automatically saved when a new portal is created so I'm wondering if this is also related. We'll address the above 2 issues in a new release early next week. In the meantime, please confirm that you do have the correct build installed (x86 vs x64) based on your Azure App setting. By default, Azure Web Apps are running in 32 bit (x86).

**Comment by paulfijma** [comment]
Hi, meetMandeep :-) thanks for responding. 
additonal information: 
i run the vanjaro installation from a 64bit windows server 2016 (4 core / 8Gb on SSD) and have azure SQL as a database.  (i tested also with upgraded SQL to 10 DTU, but that did not improve my results. (performance might be an issue... but i doubt it. since i use this setup for over 4 years now (made a fresh new database). One site kept failing install, i ran it on the local server and that worked. I don't know why that makes a difference. Network connections are solid > 100Mbit (most 1Gb up/dn)
It might be cloudflare, but then i would expect problems with all site installations.

**Comment by meetmandeep** [comment]
@paulfijma Can you confirm if this issue still persists with the latest Beta?
