### ISSUE TITLE
Vanjaro hangs and becomes un-responsive.

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1235]
**Describe the bug**
This is very random and no known specific trigger by me. I will be working along and open or close the Vanjaro Menu bar or even just simply publish the page and the site becomes completely un-responsive as shown in the attached screen shot. I have to refresh the browser to get things responsive again.....

**To Reproduce**
Random no specific function

**Expected behavior**
Operation completes and returns control to the user

**Current behavior**
Vanjaro becomes un-responsive

**Screenshots**
![image](https://user-images.githubusercontent.com/6786299/118015321-c6745880-b319-11eb-9cec-b05b7dbaae4a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version current

**Comment by meetmandeep** [comment]
@scottw12 I've seen this before and there are many causes for this and many have been resolved as well. 

Next time, be sure to open the developer tools (F12 in Chrome) and look at the console for errors. Please provide a screenshot of the error. Thanks

**Comment by scottw12** [comment]
I am very familiar with the dev tools in several browsers :-)  Here is the console error:

Some cookies are misusing the recommended “SameSite“ attribute 7
Cookie “returnurl” has been rejected because it is already expired. UserLogin
Some cookies are misusing the recommended “SameSite“ attribute 33
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. dev.jcesba.org

Uncaught TypeError: $.ServicesFramework is not a function
    <anonymous> https://dev.jcesba.org/DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/uxmanager.min.js?cdv=264 line 20 > eval:1
    success https://dev.jcesba.org/DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/uxmanager.min.js?cdv=264:20
    c https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    fireWith https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    l https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    o https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    send https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    ajax https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    ajax https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:2
    GrapesjsInit https://dev.jcesba.org/DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/uxmanager.min.js?cdv=264:20
    VjInit https://dev.jcesba.org/DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/uxmanager.min.js?cdv=264:20
    c https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    fireWith https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    l https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    o https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    send https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    ajax https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    ajax https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:2
    i https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    VjInit https://dev.jcesba.org/DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/uxmanager.min.js?cdv=264:20
    <anonymous> https://dev.jcesba.org/DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/uxmanager.min.js?cdv=264:20
    dispatch https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    handle https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    add https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    add https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:2
    ke https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    each https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    each https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    ke https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    on https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    r https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:2
    <anonymous> https://dev.jcesba.org/DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/uxmanager.min.js?cdv=264:20
    e https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    t https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    setTimeout handler*l/< https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    c https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    fireWith https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    fire https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    c https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    fireWith https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    ready https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    B https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    EventListener.handleEvent* https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    <anonymous> https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
    <anonymous> https://dev.jcesba.org/DependencyHandler.axd/83feaba0ae50c419c8762a7c4eb1e945/264/js:1
uxmanager.min.js:1:35

**Comment by meetmandeep** [comment]
Thanks @scottw12 This helps a lot.

**Comment by mksmanish79** [comment]
FIxed in #1254 and will be available in next release
