### ISSUE TITLE
Not all Images placed in /portals/0/images will sync

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1236]
**Describe the bug**
Failure of sync function on image folder

**To Reproduce**
1. Copy and paste a image into the /portals/0/images folder with a "_" in the name
2. Goto Site -> Assets click on Sync this folder
3. Image is not added to the list of images

**Expected behavior**
image is added to the library

**Current behavior**
Image is not listed

**Additional context**
If you rename the file without a _ it will show in the library after sync. You can however upload the image with a underscore  and it works fine.

**Comment by meetmandeep** [comment]
@mksmanish79 Can you duplicate this and confirm if this is a DNN or Vanjaro issue?

**Comment by meetmandeep** [comment]
@scottw12 We're unable to duplicate this issue on a clean Vanjaro Install. It works fine with a filename that has an underscore. Also, this is core DNN functionality and Vanjaro really does not play any role so you may want to investigate your DNN Instance.

**Comment by scottw12** [comment]
It was a system issue not related to DNN or Vanjaro. I am closing this issue.
