### ISSUE TITLE
Reset password link fails.

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1252]
**Describe the bug**
When I use "Lost your password? " I am sent to a link which fails 

**To Reproduce**
1. Click on "Lost your password" from the sign-in form
2. Fill out email and submit
3. Email arrives and I click on the reset link

The actual link in the email is: https://dev.jcesba.org/site/signup?ctl=PasswordReset&resetToken=8cd2dcda-764b-46ef-b2d2-c774af5dfea3

When clicked you end up on:  https://dev.jcesba.org/site/signin/ctl/passwordreset/resettoken/8cd2dcda-764b-46ef-b2d2-c774af5dfea3

With the following error:
![image](https://user-images.githubusercontent.com/6786299/118172443-fdb63880-b3f1-11eb-9994-cb92ad869436.png)

**Comment by hshimanshusharma** [comment]
@scottw12  Unable to duplicate the issue, please comment reply with site logs,
Does the issue reproduce with a new vanjaro installation?

**Comment by scottw12** [comment]
I set you up on May 20th but see you have not logged in yet.

Do you still want in?

**Comment by hshimanshusharma** [comment]
Thanks for reporting the issue and we can duplicate the issue, we will fix the issue in next build
