### ISSUE TITLE
Disable 'my profile'

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#1256]
The sign in component has several option to show/hide stuff. But the 'My profile' leads to one of the most useless and ugly looking DNN pages (hasn't had TLC for 8 years or so) so I would really likt to disable that. Or if I knew what block it was, I'd copy the block and remove the link.

![image](https://user-images.githubusercontent.com/9091997/118313447-06426800-b4f3-11eb-8054-36543f852fbb.png)

**Comment by meetmandeep** [comment]
@Tychodewaard In future, please use the Bug or Feature Request template when creating issues. 

Vanjaro Platform automatically creates a Profile Page for your with Vanjaro Profile Block that has a modern UI to edit or manage profile. If you're using Vanjaro for DNN then you need to create a new Vanjaro Page and set it as Profile page. 

I'll keep this issue open as a feature request to add the toggle to Show / Hide Profile Link in "Sign In & My Account" block
