### ISSUE TITLE
Live Slider doesn't autostart

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#1267]
**Product & Version**
Live Slider 8.0.7 / Vanjaro for DNN 1.0.5 / DNN 9.9.2 

**Describe the bug**
The animations don't initially start when viewing the page unless the user takes action like clicking prev/next. Then it runs as expected. 

**To Reproduce**
1. Create a Live Slider instance with default settings, two slides, and at least one layer element in slide 1
2. Publish the page
3. "minimize" Vanjaro (collapse to the left) and notice the display
4. Slide #1 appears, static and without animation
5. Click prev/next to initiate the animation, which will then run continuously, as expected

**Additional context**
No browser errors and no log errors.

**Comment by meetmandeep** [comment]
@eswanzey Can you refresh the page after step 4 and confirm if auto start works?

**Comment by eswanzey** [comment]
no, it still remains static.

**Comment by hshimanshusharma** [comment]
Fixed In #1141 will be available in next release
