### ISSUE TITLE
Persona Bar replaced by Vanjaro Bar on DNN pages - cookie corruption?

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#1277]
**Product & Version**
Vanjaro for DNN 1.05 on 9.9.2 

**Describe the bug**
After working for a while back and forth between Vanjaro pages and DNN pages, the Persona Bar is typically replaced with a non-functional Vanjaro Bar instead.

**To Reproduce**
1. While logged in as an admin, navigate back and forth between Vanjaro pages and DNN pages.
2. After a period of time (sometimes a few hours, sometimes the following day), navigate to DNN pages and notice that the Persona Bar no longer appears as expected, and is replaced with the Vanjaro panel that is non-functioning.

**Screenshots**
The screenshot shows a DNN page with a Porto Bar and a Vanjaro Bar, instead of the expected Porto Bar and Persona Bar.

**Additional context**
The workaround when this happens is to clear cookies and login again, which restores the expected Persona Bar functionality on DNN pages.

![image](https://user-images.githubusercontent.com/8103212/118824555-f1196080-b887-11eb-83a3-5eb509428d01.png)

**Comment by eswanzey** [comment]
Here is more odd behavior that I believe relates to this issue. 

1. Notice in the screenshot that the Vanjaro login page has two tabs. When changing the settings on the signin block, the second tab disappears, leaving just the Vanjaro sign-in. When published, it reverts back two having the two tabs, and the second tab doesn't work anyway.
2. Notice also the additional login prompt in the screenshot - it often appears after attempting to login
3. In this case, email address doesn't work for logging in. Only username does.
4. But, if a DNN page is created with an account login module on it, logging in with email address works.

![image](https://user-images.githubusercontent.com/8103212/119099499-f63ff200-b9e4-11eb-8cbe-fb1d5e8ca71f.png)

**Comment by eswanzey** [comment]
The really odd behaviors I was seeing were caused by the fact that there were a few dozen user accounts that had duplicate email addresses. The site is set for email address as username. Clearing out these redundant accounts restored most of the login functionality.

However, the Vanjaro signin page still has the Standard tab visible, the Standard tab login doesn't work anyway, and the Vanjaro tab only recognizes username and not email when logging in.

**Comment by hshimanshusharma** [comment]
@eswanzey  We have tried multiple times but we were unable to duplicate the issue on our side.
If the issue occurs again on your site, then install EditThisCookie(Chrome Extension) and provide a screenshot of your cookies.

**Comment by eswanzey** [comment]
@hshimanshusharma Thank you. I was able to resolve all of these odd behaviors and issues. This was a v3-era multi-portal installation that had been extracted years ago using portal deletion, then after adding 100K users over the years, was converted to use email address as username. Needless to say, the membership database needed some attention. The most important fact is that Vanjaro caused none of it, and now responds extremely well on this hybrid installation.

**Comment by eswanzey** [comment]
I don't know how else to best ask the question on this - do you think that the updates on this will also resolve the issue where the secondary login prompt appears will be resolved as well? What I'm talking about is the screenshot you see about 4 replies back on this thread where IIS throws an additional login prompt.
