### ISSUE TITLE
Live Forms  screen jitter problems - Vanjaro only

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1323]
**Product & Version**
Vanjaro for Platform RC2 

**Describe the bug**
See attached screencast.  When editing a live form in Vanjaro I get a jittery screen when trying to scroll the bottom of the form into view. I am reporting here because it does not happen to me in a pure DNN install.

http://somup.com/crhOoKqIqF

**Comment by meetmandeep** [comment]
This indeed seems like a Live Forms issue. I've logged this issue over at Mandeeps.com for resolution. Feel free to reach out to Mandeeps.com with any other information or concerns. Thanks
