### ISSUE TITLE
Cannot change database name in the Installer

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1338]
**Product & Version**
Vanjaro Installer

I cannot change the name of the database. I have a specific naming convention for my SQL server. I need to be able to change the DB name in the installer in order to install.

![image](https://user-images.githubusercontent.com/6786299/119860849-5b5f8000-bedc-11eb-9957-a977c22aa6b7.png)

**Comment by meetmandeep** [comment]
There are no plans to support this at this time. Vanjaro uses its own naming convention to figure out which database to delete when deleting the site. Perhaps, only use the Installer for test/dev/staging and use a manual install method for production with your own naming convention.
