### ISSUE TITLE
Webp not applied

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#1354]
**Product & Version**
RC2

**Describe the bug**
If I verify tjeps.com in google page speed, I get the suggestion to offer images in modern extension like webp. But I thought that was done automatically...

**To Reproduce**
Visit https://developers.google.com/speed/pagespeed/insights/?hl=nl&url=https%3A%2F%2Fwww.tjeps.com&tab=mobile

**Expected behavior**
To not have this suggestion and hopefully a few points added to the score :-) 

**Screenshots**
![image](https://user-images.githubusercontent.com/9091997/120182204-608b3a80-c20e-11eb-8b80-13fd8bc9d2ec.png)
![image](https://user-images.githubusercontent.com/9091997/120182365-94fef680-c20e-11eb-9893-2fde18a8a7e4.png)

**Additional context**
Some images are uploaded by me, other inserted via Pixabay.

**Comment by Gaganbird** [comment]
Section block uses background image and does not support webp (picture tag).

I would recommend you add an image block in the section block instead of using a background image.

**Comment by Tychodewaard** [comment]
will be closed by #1367
