### ISSUE TITLE
Live Blog Widgets not configurable.

### ISSUE THREAD

**Issue by ecotto7** [vanjarosoftware/Vanjaro.Platform#1365]
**Product & Version**
RC2

**Describe the bug**
Live Blog Widgets do not work.  After dropping the Live Blog Widgets onto a page.  There is no way to configure it.  Only comes up as a blank Block.  The manage button takes you to the blog page but not to a place where you can select the widget you want to display.

**Comment by scottw12** [comment]
LiveBlog Widgets worked in RC1 as I have set up several. But in RC2 Manage link takes me to the main blog admin page.

https://screencast-o-matic.com/watch/cr1nbqVhU01

This is on Vanjaro Platform

**Comment by scottw12** [comment]
I also have the same problem with LiveArticles. I will post this to Mandeeps Support.

**Comment by mksmanish79** [comment]
We are able to duplicate the issue and will be fixed shortly.
