### ISSUE TITLE
Custom Code Block not visible when it only has script in it.

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1384]
**Product & Version**
RC2

**Describe the bug**
When you add a custom code block to the page and only use it for script . It has no space assigned to display in edit mode. The only way you can find it is to remember where it is at and find it in the navigator...

Also the code does not display in preview mode

This is the code: <script type='text/javascript' src='https://www.rapidscansecure.com/siteseal/siteseal.js?code=115,4A164A24C8AF4BB1FDE9490D8040B65A1ED1AA6C'></script>

**Expected behavior**
A block with controls for moving editing etc

**Screenshots**
![image](https://user-images.githubusercontent.com/6786299/120708952-d945fd00-c481-11eb-85a5-ea0d8a381171.png)

**Comment by scottw12** [comment]
I have verified that this is the behavior in a complete fresh install.
http://somup.com/cr1jD9qwkt

**Comment by meetmandeep** [comment]
@scottw12 Why add just a script tag in a Custom Code block. Blocks are meant for content (presentation). You can just as easily include a script from Page Header tag. 

I suppose we can add a minimum height to the Custom Code block to solve this issue; the only concern is that it changes how the page appears in Edit Vs. View mode.

**Comment by scottw12** [comment]
You add it when, the company that provides verification that you comply with PCI DSS best practices, requires it to be in a certain position on your page. :-)
![image](https://user-images.githubusercontent.com/6786299/121256487-3b33a780-c872-11eb-911c-08f1bf0a1906.png)

This is what Aperia requires us to add to the page and it cannot be in the footer. It either has to be just prior to the ecommerce form or just below the submit.
  
<script type='text/javascript' src='https://www.rapidscansecure.com/siteseal/siteseal.js?code=115,4A164A24C8AF4BB1FDE9490D8040B65A1ED1AA6C'></script>

**Comment by meetmandeep** [comment]
Makes sense. We'll try and add minimum height so you can still access the controls.
