### ISSUE TITLE
Vanjaro as stand-alone extension?

### ISSUE THREAD

**Issue by ashishpachauriap** [vanjarosoftware/Vanjaro.Platform#14]
Smooth installation of Vanjaro,no issues at all and working in a couple of minutes. But I'm wondering if I'll be able to use Vanjaro in other DNN sites that I've already have. Will be Vanjaro available as an stand-alone extension that I can install on any DNN?

**Comment by meetmandeep** [comment]
Vanjaro will be available as a Stand Alone extension beginning with Alpha 3.

**Comment by meetmandeep** [comment]
Vanjaro is now available as a DNN Extension.
