### ISSUE TITLE
Cannot update a Custom Code Block. 

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1414]
**Product & Version**
RC2 Platform

**Describe the bug**
I cannot update an existing Custom Code Block

**To Reproduce**
Create a Code block and try to edit it.

**Expected behavior**
Should be able to edit and save a current Code Block

**Current behavior**
Cannot Update

**Screenshots**

**Additional context**
Custom Code blocks are a handy tool for content and can become very complex. 
However there is no way to update a current Custom Block. 
From time to time a  Custom Code Block may need something updated. 
The only way I see I can do that now is:
1. Copy the block 
2. Edit the copy
3. Save the edited copy under a different name 
4. Delete the original Custom Code block
5. Place the changed block on a page
6. Save block  with old name
7. Then delete the changed block.

http://somup.com/cr16bmqaoX

**Comment by Gaganbird** [comment]
There is no update feature in the custom block at this time. You may follow the below steps:

> Drag the custom block on the page 
> Delete the original custom block
> Edit the dragged custom block
> Save it with the same name
