### ISSUE TITLE
Classes not stored in global block

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#1442]
**Product & Version**
RC2, DNN 991

**Describe the bug**
If you  add a class to a global block, the class is not picked up by other instances of the global block. 

**To Reproduce**
Have 2 pages using the same global block
Add a class to the global block
Verify other page with the same global block

**Expected behavior**
Like other content or styling, I expect that any changes on the global block reflect on other instances of that same block

**Comment by meetmandeep** [comment]
> If you add a class to a global block, the class is not picked up by other instances of the global block.

That is the intended behavior. Each block is a unique instance; including the Global Block. Everything inside the Global Block is persisted across all instances. So in this use case, add the class to a section inside of a global block and all other blocks can be nested in this section.
