### ISSUE TITLE
Add 'nav' as a section type.

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#1450]
![Screenshot 2021-06-17 110902](https://user-images.githubusercontent.com/1585717/122424112-744bd600-cf5c-11eb-8fa6-f04ea3227103.png)

**Comment by meetmandeep** [comment]
Not needed. Nav tag is auto created by the menu block.

**Comment by X3Technology** [comment]
But the Menu block auto-populates from the pages hierarchy.  What if I want to create a stand-alone menu of hard-coded links.  The proper HTML5 tag would be `<nav>` for semantic HTML.

**Comment by meetmandeep** [comment]
That's a valid point for custom built menus. I know that it was an available option before and it was removed. I'll keep this issue open until design team can chime in. Thanks
