### ISSUE TITLE
Apply Theme should auto-refresh

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#1451]
I copied the 'Basic' theme folder in /Portals/_default/ so I could play around with a new theme.
When I got Site -> Design -> Themes, I see the new theme that I just copied and I can click the context menu and select Apply.  However, nothing appears to happen.  The theme I selected still has the "Apply" option and the 'Basic' theme is still selected, which feels like nothing happened.  

After I restarted the application and went back and it now correctly shows my new theme as selected, so it appears the change took effect but is just not reflected in the UX at first.

**Comment by meetmandeep** [comment]
> I copied the 'Basic' theme folder in /Portals/_default/ so I could play around with a new theme.

So themes work a little differently in Vanjaro. You can't simply copy the folder. Themes require a server side component and must implement ITheme interface. I would recommend holding off on this until documentation is in place for development.
