### ISSUE TITLE
Add ability to define custom Id attribute to design blocks

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#1453]
Basic blocks like Section have the ability to define a custom Id attribute.
![Screenshot 2021-06-17 131851](https://user-images.githubusercontent.com/1585717/122444500-9cdccb80-cf6e-11eb-90da-c01b0168cd1b.png)

Design blocks like Logo have the ability to add custom classes, but not define a custom Id.  Is that possible?

**Comment by meetmandeep** [comment]
@mathisjay Please use discussions to ask questions, suggest ideas, and general conversations. Only use issues when reporting a bug or suggesting a feature. Be sure to follow the issue template. Thanks
 
No. The idea is to keep everything automated and as simple as possible. You can customize ID on section to specify your own anchors for singe page websites or to link to a named anchor rather than arbitrary ID. Example: #buynow

**Comment by X3Technology** [comment]
Having an ID on an element also makes it easier to target with custom CSS.  I realize that I could set the styling choices directly using the designer, but if I was trying to reuse an existing CSS stylesheet, it might be easier to just give the element the proper ID, rather than try to rebuild the styling using the designer.

**Comment by meetmandeep** [comment]
> Having an ID on an element also makes it easier to target with custom CSS

Sure. You can still do that by using the parent (Section) ID with scope. Example: #mySection .myClass / button

The fundamental reason for this choice is that Vanjaro is all about User Experience (as in End User) and not developer focused at all. Every technical decision, attribute, or information is masked from end user. An end user doesn't care what IDs are and they simply add to a cluttered UI that is hardly used.

**Comment by X3Technology** [comment]
I urge you to reconsider.   I understand the desire for a user-centric experience.  But, there is still a very valid use case for allowing the ability to customize the ID.

Even Wix does this.  They purposely make it somewhat difficult to get there, but it's possible for advanced users (a.k.a. developers).    You have to first enable "Dev Mode" and then you get access to some advanced functions like the attached screenshot.

![custom_id](https://user-images.githubusercontent.com/1585717/122556958-27bed400-d00a-11eb-89b3-63ec0b973535.png)

Consider adding an "Advanced" or "Developer" link somewhere to the Styling UX tab that would expose additional functionality that the average novice user would never use.  Even the ability to add custom classes could go there as most novice users would never need to see that.

**Comment by meetmandeep** [comment]
> Consider adding an "Advanced" or "Developer"

This is precisely why we didn't consider adding ID to every attribute. I suppose we could consider "Advanced" or "Developer" mode in future if there are enough use cases but the idea is to not have to fiddle with code. We rather invest time and effort in creating native functionality so there is no need to manually change IDs.

**Comment by X3Technology** [comment]
Totally get that and I love the idea of no-code or low-code. Just seems like there is always some use case that doesn't quite fit into the UX that's available and lower-level access is needed to get the job done.  I like the idea of an opt-in function like "DevMode" that shows the lower-level stuff that most people will never need/want to see.
