### ISSUE TITLE
When type a URL into messages or apps like teams Vanjaro message is displayed.

### ISSUE THREAD

**Issue by ecotto7** [vanjarosoftware/Vanjaro.Platform#1474]
**Product & Version**
RC 1.5

**Describe the bug**
When type a URL into messages or apps like teams Vanjaro message is displayed.  Instead of the page description.

**To Reproduce**
1. Paste site Url into, Messages, Teams, or Skype
2. Vanjaro message displays.  See screenshot

**Screenshots**
<img width="703" alt="Screen Shot 2021-06-22 at 6 29 53 PM" src="https://user-images.githubusercontent.com/30248037/123008167-634dfb00-d388-11eb-9c73-1baac84a52f1.png">

**Comment by meetmandeep** [comment]
Did you change your site title and description from Menu > Settings > SEO ?

**Comment by Tychodewaard** [comment]
I have the same issue:
On SEO there is 
![image](https://user-images.githubusercontent.com/9091997/123062869-34c63380-d40d-11eb-8cf3-962c437d6d66.png)

When sharing on whats app:
![image](https://user-images.githubusercontent.com/9091997/123062949-44de1300-d40d-11eb-964d-2c7548d0c226.png)

**Comment by ecotto7** [comment]
As you can see from Tychodewaard's screenshot there is no place to add description,

**Comment by meetmandeep** [comment]
We'll get this resolved right away. Thanks @Tychodewaard & @ecotto7
