### ISSUE TITLE
Site-Pages corruption

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#1497]
**Product & Version**
RC2
**Describe the bug**
I created a home02 as I wanted to replace the old one.
Renamed home to home03
deleted home03 also from trash
renamed home02 to home
and from that moment on if I click Site - Pages I get the following:

![image](https://user-images.githubusercontent.com/9091997/124144940-b0b72000-da8c-11eb-9b3b-249ce0675736.png)

**Comment by ecotto7** [comment]
I had the same issue.  I had to go into the database and manually fix.

**Comment by Tychodewaard** [comment]
Would you be so kind to tell how you fixed it?

**Comment by ecotto7** [comment]
I went into the Tabs table fixed the tab names and changed the isDelete to false.

**Comment by Tychodewaard** [comment]
So, you basically reverted the actions?


Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Elliot Cotto ***@***.***>
Verzonden: Thursday, July 1, 2021 9:48:55 PM
Aan: vanjarosoftware/Vanjaro.Platform ***@***.***>
CC: Tycho de Waard ***@***.***>; Author ***@***.***>
Onderwerp: Re: [vanjarosoftware/Vanjaro.Platform] Site-Pages corruption (#1497)


I went into the Tabs table fixed the tab names and changed the isDelete to false.

**Comment by ecotto7** [comment]
Yes.  I know it is not much of a solution.  Now I just wipe out all the elements on the Home Page and use the original Home Page.  Or I take the new page and turn all the elements into a Custom Block and Drop them on the original blank Home Page.

**Comment by hshimanshusharma** [comment]
Try to clear/disabled browser cache or use browser private tab, browser cache the page URL,
