### ISSUE TITLE
Remove unnecessary nodes from web.config 

### ISSUE THREAD

**Issue by narensingh008** [vanjarosoftware/Vanjaro.Platform#151]
![image](https://user-images.githubusercontent.com/13765669/94673086-d368ac80-0333-11eb-9600-6433ed349560.png)
![image](https://user-images.githubusercontent.com/13765669/94673088-d499d980-0333-11eb-8682-ce6911604d33.png)

**Comment by hshimanshusharma** [comment]
The below image issue has been fixed don't work on it.
![image](https://user-images.githubusercontent.com/13765669/94673086-d368ac80-0333-11eb-9600-6433ed349560.png)
