### ISSUE TITLE
Digital asset management module does not work and throws multiple js errors 

### ISSUE THREAD

**Issue by Gaganbird** [vanjarosoftware/Vanjaro.Platform#152]
![image](https://user-images.githubusercontent.com/52308516/94678710-8937f900-033c-11eb-8592-1f946b7e09d7.png)

**Comment by meetmandeep** [comment]
Vanjaro includes its own Asset Manager. DNN is also set to deprecate Telerik Based Asset Mananger in DNN 10.x so this is a non-issue.
