### ISSUE TITLE
Menu Bar

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1575]
It would be nice if the menu bar stayed on Pages after a page delete...

Right now when doing a delete the Menu bar goes back to the BLOCKS tab. So the user has to click on the hamburger -> Site -> pages to get back to a page to edit.

**Comment by meetmandeep** [comment]
I'm unable to duplicate this. The menu stays on pages if I delete a page. If you happen to delete the page you're currently viewing then the site will refresh and it will go back to blocks tab.

**Comment by scottw12** [comment]
My bad. I had switched over to another test site and had not yet been updated to 1.1.0
In version 1.1.0  it works correctly
I will close this.
