### ISSUE TITLE
Fonts tab disappeared

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#1579]
**Product & Version**
DNN 9.9.1, Vanjaro 1.1

**Describe the bug**
If I want to add fonts (which was very easy and still working in RC2), I don't see the tab anymore to do this.
I recorded it on https://www.youtube.com/watch?v=frbEa7XSMPY

**To Reproduce**
Recording. Note, these installs are both upgrades from beta-rc1-rc2-1.1

**Expected behavior**
Tab is present so I can add fonts again like in RC2

**Comment by mksmanish79** [comment]
You can easily add/remove fonts from Site > Design > Theme > Settings > Custom > Settings > Fonts

**Comment by Tychodewaard** [comment]
Ah, I took the wrong tour...
