### ISSUE TITLE
Cannot Select Icon Box to Edit

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1627]
**Product & Version**
v1.1

**Describe the bug**
I cannot select the icon box either in screen or from the navigator.

**Expected behavior**
I expect to be able to select icon box so I can edit its properties.

**Current behavior**
No way of selecting. on screen select icon and then when you press the up arrow it skips icon box and goes to column. Click on iconbox in the navigator and nothing happens.

**Screenshots**

**Additional context**
Add any other context about the problem here including the Browser/OS version.

**Comment by Gaganbird** [comment]
That is by design. Icon Box is merely a container for Icon and cannot be directly selected or styled.
