### ISSUE TITLE
Remove unused DNN files from Vanjaro distribution

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#1630]
While watching the install package unzip, I noticed a whole bunch of CSS file and other stuff getting unzipped that I suspect are not used in Vanjaro.  It would be nice to remove all of these to have a clean install without all the bloat that DNN has accumulated  over the years.  For example, I noticed a bunch of stuff in the /Resources folder that could probably be removed.  Probably lots of other clean up opportunities as well.

**Comment by meetmandeep** [comment]
Vanjaro Platform includes a minimal copy of DNN Distribution. Learn more at: https://github.com/vanjarosoftware/Vanjaro.Platform/wiki/Vanjaro-Platform

These unused files are kept for compatibility with existing DNN Extensions that may depend on it. Eventually, we will remove all unused files when the extensions are natively compatible with Vanjaro or alternatives are available. The timing for that will be organic and based on community direction.

**Comment by X3Technology** [comment]
Good point.  Can't wait until we can finally dump all that technical debt, but we will have to live with for time being.
