### ISSUE TITLE
Add 'rem' as a unit choice for padding/margin etc.

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#1631]
On the style editor, the only selectable unit choices are 'px', '%', 'vw', and 'vh'.

![rem](https://user-images.githubusercontent.com/1585717/129929652-458afdaa-293e-453d-b0e2-f32600ff7aaf.PNG)

Please add 'rem' and the other valid unit choices.

https://www.w3schools.com/cssref/css_units.asp

**Comment by meetmandeep** [comment]
rem is "relative to font-size of the root element"; it does not apply to padding. You will find "rem" as a valid option for font-size.

**Comment by X3Technology** [comment]
Although relative to the font-size, 'rem' is simply a unit of measurement and it absolutely a valid unit for padding, margin, width, or any other CSS property that expresses a length.

https://www.w3schools.com/cssref/css_units.asp
https://discuss.codecademy.com/t/can-i-use-responsive-units-like-em-and-rem-for-margin-and-padding/361260
https://www.reddit.com/r/css/comments/50tyfj/should_i_use_rem_and_em_units_on_margin_and/

I see 'rem' used all the time in commercial themes.  Consider if you had an H1 tag and wanted the padding around the text to be relative to size of the text.  If you used an absolute unit like 'px' and then changed the size of the H1 tag, you would then also have to change the size of the padding, but not if you used 'rem'.

Is there some reason to not have the other units of measurement as an option?  It's valid CSS.

**Comment by meetmandeep** [comment]
Thanks for the detailed use case. Makes sense. We'll add this in.
