### ISSUE TITLE
navbar class CSS

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#1632]
Somewhere in the Vanjaro CSS this happens:
![navbar css](https://user-images.githubusercontent.com/1585717/129932069-6e1db734-f1cc-4ce4-b409-3cc2a163e6bc.PNG)

This isn't in the the vanilla BS5 CSS, so it must be coming from some add-on Vanjaro source.

Please remove the '!important' directive.  It is entirely legitimate that someone would want to use the .navbar class on an element and have padding, but this CSS will prevent any padding, even if we use the style editor to set an explicit value.

**Comment by scottw12** [comment]
Go to the V on your UX Toolbar. And click on Enable Debug Mode. This stops the resource management and leaves the css and js files as standalone for debugging. You would see template.css or portal.css in you browser debug instead of css:6

**Comment by X3Technology** [comment]
Thanks!  This tip was actually very helpful.  I learned that portal.css is being loaded first before the version of BS5 and all of the CSS that Vanjaro adds.  It should be loaded last.  I will create a separate bug ticket for it.

**Comment by X3Technology** [comment]
To the original ticket, I was finally able to determine where this odd CSS was coming from.

In the template.editor.json file included in the vTheme folder, approximately line 277.  From what I guess, it appears this file uses the "Sass" value to add some custom CSS to the theme.css file that gets generated when you save the settings from Design->Themes.  The value within the Sass string are not editable via the UX and are basically hardcoded CSS rules.  

That's not great, but I suppose I could understand the desire to hide some settings from the user.  It would be better if the UX exposed this CSS somehow rather then requiring someone to dig through a JSON file.  Is the long term plan to expand the UX to include the ability to manipulate all of these CSS rules that are currently hardcoded?
