### ISSUE TITLE
Add ability to link external CSS AND control priority

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#1633]
I would really lie to be able to link an external BS5 CSS file (from something like ThemeForest) to shortcut theming and not have to rebuild all the CSS rules in the Vanjaro Style UX. 

I realize I can link the file in the Settings->SEO->Advanced->HTML Page Header Tags:
![Capture1](https://user-images.githubusercontent.com/1585717/129951400-6e61625f-62f9-4099-b294-8b4e94dac348.PNG)

This is great.  However, the DependancyHandler then loads the concatenated Vanjaro CSS after my external stylesheet:
![Capture2](https://user-images.githubusercontent.com/1585717/129951496-bfff7084-e6d0-4eb8-9c12-1201d8a7e195.PNG)

It would be helpful  if there was some utility to add external resource file (CSS and JS) and control when/where they are loaded.

**Comment by Tychodewaard** [comment]
You can just import in custom styling (basically portal.css), right? So, @import

**Comment by X3Technology** [comment]
Where would I do that?

Sent via the Samsung Galaxy S20 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tychodewaard** [comment]
Design - Custom styling.
![image](https://user-images.githubusercontent.com/9091997/129955208-a14db6f5-4123-4757-a8b3-335b95a959b9.png)

Or /admin and use the DNN interface to add the css

**Comment by X3Technology** [comment]
I like this idea for a couple of reasons, not the least of which is that it eliminates an HTTP request and caches the CSS in the DependancyHandler.

However, I am still running into some priority issues from within the DependancyHandler.

Consider this:
![navbar](https://user-images.githubusercontent.com/1585717/129957062-b613de1e-9665-4922-9cc2-54df27bdaba7.PNG)

Here I have an element that I used the .navbar class.
In the console, we see the following rules being applied for padding-top:

1. 1.25rem - this comes from my custom CSS which was - read first
2. 0px !important - read second - dont know where this comes from, but the !important overrides all the subsequent rules
3. 0.5rem - read third - this is the default BS5 rule for .navbar
4. 20px - read last - this was set using the Vanjaro UX directly on the element.

Ideally, 
- remove the 0px !important rule.  Not sure why this is here or where is comes from, but I don't want it
- allow me to specify that my CSS file load after the default BS5 CSS so the custom theme will override the default
- I could then eliminate my tag specific CSS that I added with the Vanjaro UX style editor, (which really should have overriden the second rule above)

**Comment by Tychodewaard** [comment]
AFAIK the portal.css is loaded last. So, adding the css in the portal.css including !important; overwrites the previous. Admitted: it is a bit silly but you can move forward.

**Comment by X3Technology** [comment]
I know in vanilla DNN, portal.css is loaded last in the DependancyHandler.   But I think Vanjaro is loading their version of BS5 after portal.css.  

So, right now, the only way to move forward is to explicitly provide an duplicate CSS rule that adds '!important' for any rules in my custom CSS file that get overridden by the Vanjaro stuff.  

Feels a lot like having to override all the crap CSS rules that were included DNN's default.css when building a DNN skin.

The best solution would be to incorporate the functionality already built into DNN with the ClientResourceManager for adding JS and CSS files and specifying when/where they are loaded.

Something like:
ClientResourceManager.RegisterStyleSheet(this.Page, ResolveUrl("/DesktopModules/ecredable2/plugins/select2/select2-bootstrap.css"), 2);

There are also user controls that do this declaritively: JsInclude and CssInclude

Build a UX around this functionality and include in the Settings section.

**Comment by X3Technology** [comment]
I enabled Debug Mode and I can confirm that portal.css is being loaded first...

**Comment by X3Technology** [comment]
![portalcss](https://user-images.githubusercontent.com/1585717/129981182-8e67f73e-4a38-4a38-9d8b-1ba49a19734f.PNG)
