### ISSUE TITLE
cannot access installation after domain modified

### ISSUE THREAD

**Issue by aloscher** [vanjarosoftware/Vanjaro.Platform#1643]
**Product & Version**
Bug applies to Vanjaro Platform 

**Describe the bug**
redirect error cannot access my website after altering the default domain

I thought I had a one-off problem but it has happened a few times and I had to re-install the Vanjaro Platform.

Under setting->Domain I had two domains and changed the default. I could no longer access the install due to a re-direct error.

This has happened a few times to me.

**Comment by meetmandeep** [comment]
We're unable to duplicate this issue. It could be a browser cache issue; try clearing the browser cache or opening in an incognito window. If the issue persists, please provide a screencast. Thanks
