### ISSUE TITLE
Locked out of Vanjaro after adding reCAPTCHA

### ISSUE THREAD

**Issue by aloscher** [vanjarosoftware/Vanjaro.Platform#1645]
**Product & Version**
Bug applies to Vanjaro Platform

**Describe the bug**
After adding ReCaptcha cannot log in to site

message 
"We couldn't determine if you're human or robot. Please try again."

**Current behavior**
I am now locked out of my install

**Screenshot**
Attached

![image](https://user-images.githubusercontent.com/21082075/130329766-0d5f87ef-600a-4de2-9516-a6e83b94db11.png)

**Comment by aloscher** [comment]
This could be firewall-related.  I had an issue with using pixabay as well.

**Comment by meetmandeep** [comment]
Yes. Vanjaro needs to check with Google's Server to validate the captcha. You can manually turn ReCaptcha OFF by executing the following SQL Query directly on database:

update HostSettings set SettingValue='False' where SettingName='Vanjaro.Integration.Captcha.Enabled'
update PortalSettings set SettingValue='False' where SettingName='Vanjaro.Integration.Captcha.Enabled'

Note: The above query will remove ReCaptcha from All Sites / Host Level.

**Comment by scottw12** [comment]
Need to re-think this... I setup captcha after  a couple weeks of running v1.1.0 and now I am having the same issue as the op reported. I have waited for 4 hours and still cannot login.  I did set up captcha at the global level. And there has been no firewall changes here. And of course I  haven't found any log entries yet. 

The following is the error on the browser devtools:
GET https://www.google.com/recaptcha/api.js?render=6Lf_ZsobAAAAABenfEjNODJnMJ2h6JIVM1sLxFE1 net::ERR_ABORTED 400

I am also using recaptcha on a couple Live_Forms modules and it is working fine using the same keys. As listed below. 
I do have a couple other websites on this machine using V3 and V2 of recaptcha and all is fine.

The captcha settings in global worked fine for about 2 days and no this problem....I wouldnt have reported anything but after 4 hours I decided to try again...It through the captcha error. But as I said ONLY on one Vanjaro site.  

Anyway , update HostSettings set SettingValue='False' where SettingName='Vanjaro.Integration.Captcha.Enabled' cleared up the problem for now. I will turn captcha on again tomorrow and see if the issue continues.

What version of captcha is Vanjaro_Platform using, maybe it is a captcha version issue?


(unknown) XHR finished loading: POST "https://www.google.com/recaptcha/api2/reload?k=6Lf_ZsobAAAAABenfEjNODJnMJ2h6JIVM1sLxFE1".
(anonymous) @ VM137:1
Cz.send @ VM152 recaptcha__en.js:546
(anonymous) @ VM152 recaptcha__en.js:389
hx.$ @ VM152 recaptcha__en.js:555
(anonymous) @ VM152 recaptcha__en.js:49
ER.jz @ VM152 recaptcha__en.js:553
E.Cb @ VM152 recaptcha__en.js:553
ER.send @ VM152 recaptcha__en.js:554
(anonymous) @ VM152 recaptcha__en.js:558
(anonymous) @ VM152 recaptcha__en.js:55
bZ @ VM152 recaptcha__en.js:463
Xm.send @ VM152 recaptcha__en.js:558
(anonymous) @ VM152 recaptcha__en.js:341
(anonymous) @ VM152 recaptcha__en.js:342
V$.ug.E.C @ VM152 recaptcha__en.js:693
h.G @ VM152 recaptcha__en.js:210
(anonymous) @ VM152 recaptcha__en.js:210
(anonymous) @ VM152 recaptcha__en.js:15
Y.<computed>.next @ VM152 recaptcha__en.js:30
I @ VM152 recaptcha__en.js:132
Promise.then (async)
M @ VM152 recaptcha__en.js:132
(anonymous) @ VM152 recaptcha__en.js:133
(anonymous) @ VM152 recaptcha__en.js:132
(anonymous) @ VM152 recaptcha__en.js:33
(anonymous) @ VM152 recaptcha__en.js:209
(anonymous) @ VM152 recaptcha__en.js:381
dM @ VM152 recaptcha__en.js:491
a @ VM152 recaptcha__en.js:69
I @ VM152 recaptcha__en.js:46
(unknown) XHR finished loading: POST "https://www.google.com/recaptcha/api2/userverify?k=6Lf_ZsobAAAAABenfEjNODJnMJ2h6JIVM1sLxFE1".

**Comment by meetmandeep** [comment]
> Need to re-think this...

Yes. Google ReCaptcha v3 does have false positives and this is indeed an issue. It doesn't even offer a human challenge and only provides a score. It's a bigger issue in case of network problems or connectivity issue with Google's Server; it keeps us from logging on to the site. 

We need an alternate way to confirm spam protection. I'm flagging this issue with help wanted so we can get more on eyes on this. My immediate opinion is that we need to add honeypot to the mix and use that as a secondary protection if recaptcha fails; or perhaps use that as default method. 

Any ideas from the community are welcome.

**Comment by meetmandeep** [comment]
Another ideas is 2FA; we have that on the roadmap anyways. If the ReCaptcha fails for any reason, it will send a code to the email which would be required login.

**Comment by scottw12** [comment]
That seems to be Google's recommendation.

login | With low scores, require 2-factor-authentication or email verification to prevent credential stuffing attacks.

https://developers.google.com/recaptcha/docs/v3
