### ISSUE TITLE
Sign In & My Account module - not displaying Sign Up link

### ISSUE THREAD

**Issue by puresystems** [vanjarosoftware/Vanjaro.Platform#1668]
**Product & Version**
Vanjaro for DNN
Vanjaro v: 1.1.0
DNN: 9.9.1

**Describe the bug**
The Sign In & My Account module doesn't appear to be working as expected. As per this video:
https://www.youtube.com/watch?v=Q-q5JlkPLpE

We were expecting it to show a Register and Login link when the appropriate settings were turned on but instead we just see "My Account" when not logged in - clicking it takes us to the login page. When logged in we see "My Account" with "My Profile" and "Log out" as drop-down options.

**To Reproduce**
1. Add "Sign In & My Account module" design element to a page, publish, and view this page when not logged in.

**Expected behavior**
Expected to see Register/Signup link and Login link when not logged in.

**Current behavior**
We see "My Account" when not logged in.

![account login element](https://user-images.githubusercontent.com/4923523/130966448-3c1551a4-3684-430c-9952-e63678d0529d.png)

**Comment by meetmandeep** [comment]
That's a pre-release video. 

A separate register and login link pattern was popular 15 years ago and was adopted by DNN. We opted to combine "Register" and "Login Link" in a single "My Account" link to be inline with modern sites. An option to Signup now appears underneath the login form.

**Comment by puresystems** [comment]
Thanks for confirming it's by design. Although i don't completely agree it's part of modern sites. For a site which replies on people registering, the "My Account" isn't overly obvious that it's the link to click. If we wanted to have a button in the global header for Register (and link it to the preset registration page) is there a way to use permissions to hide it to Authenticated users?

**Comment by meetmandeep** [comment]
> If we wanted to have a button in the global header for Register (and link it to the preset registration page) is there a way to use permissions to hide it to Authenticated users?

Absolutely! Add your button to a section. Use the gear icon (settings) on section to manage permissions. You can have the section visible to unauthenticated users only.
