### ISSUE TITLE
Need ability to switch page to/from "

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#1676]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by meetmandeep** [comment]
I'm not sure if I understand. Can you please provide more information and context?

**Comment by X3Technology** [comment]
Sorry.  This got saved prematurely.  This is ticket #1678.  Closing this one.
