### ISSUE TITLE
Theme designer loads cached theme.designer.json even after Theme change

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#1687]
I made a copy of the Basic theme.  I then edited the new theme.designer.json and stripped out everything except the Site->Colors controls.
![just_colors](https://user-images.githubusercontent.com/1585717/131217235-660e8dc9-7051-4367-aa35-936199cec568.PNG)

This works as expected and only shows the controls left in my new Theme. (yes, I know this breaks a whole bunch of Vanjaro blocks like Login and such, but I'm just messing around).

I then switched the Site theme back to the Basic theme, but the designer did not switch back to the collection on controls for Basic, it still loaded the same collection for my new theme.  I suspect the theme.designer.json file is cached after switching themes.  The Basic themes controls would not load until after I clicked the Save Theme button on the UX.

This is what I expected to see after Applying the Basic theme:

![basic_controls](https://user-images.githubusercontent.com/1585717/131217433-7ac63b01-3b67-4453-a9a6-1903ff5543b0.PNG)

The UX controls should switch automatically whenever switching themes.

**Comment by meetmandeep** [comment]
> I made a copy of the Basic theme. 

You cannot simply copy a theme folder and create a copy. Themes have a server side component. We will provide official documentation on how to create new theme starting next month dev series webinars.
