### ISSUE TITLE
Replace images does not work

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#1731]
**Product & Version**
Both Vanjaro cloud and Vanjaro as DNN extension

**Describe the bug**
If I have an image and I would like to replace that, that does not happen. The old image is shown. The only way to get the new image active is to add a new image.

**Expected behavior**
double click pencil, choose a new image, close overlay, new image is still there, publish, new image is still there.

**Comment by Gaganbird** [comment]
Are you talking about image editor option. Can you please provide a screenshot.

**Comment by meetmandeep** [comment]
All you need to do is double click on the image to replace it with a new image. Use the pencil icon will bring up image editor. The upload option within the image editor is to add an image mask; not to replace image.

**Comment by Tychodewaard** [comment]
https://www.youtube.com/watch?v=I2tQvgnoHN0

I closed the file manager with the arrow button which closes the box but leaves the ability to slide back open. This scenario does not allow me to publish so I need to reload to get the page published again. Closing the file manager with the x does the trick.
