### ISSUE TITLE
Required profile fields not enforced during registration

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#1766]
**Product & Version**
Vanjaro v1.1.0 on DNN v9.10.1. 

**Describe the bug**
If a profile field is made required, the requirement isn't enforced on initial registration. It's only enforced on the registrants next login.

**To Reproduce**
1. Create a required profile field and logout
2. Register as a new user
3. Notice how the registration can be completed without the required field displayed
4. Log out
5. Log back in, and the required field is requested 

**Expected behavior**
That the required field would be presented during the registration process.

**Comment by hshimanshusharma** [comment]
Profile UI breaking that why open the issue  @pankajmandeeps  please fix
