### ISSUE TITLE
3rd Party/Mandeeps Modules

### ISSUE THREAD

**Issue by ashishpachauriap** [vanjarosoftware/Vanjaro.Platform#18]
I installed a couple of Mandeeps modules. Installation works without any problems, but I am running into some issues when trying to use.

Live Slider

- When I try to upload a new image, I get a critical error. This is what the log says 'startIndex cannot be larger than length of string. Parameter name: startIndex'

 

Live HTML

- When I drag this onto the page is just disappears, as if I hadn't put it there in the first place.

**Comment by meetmandeep** [comment]
Live HTML does not render any content when it's dropped on the page; hence, it just disappears. You can get to it from Navigator. 

Live Slider issue has been resolved as well.

**Comment by scottw12** [comment]
Live Slider image issue  I still have using Vanjaro 0.5.3 (BETA) and Live-Slider v8.0.6  I do not always get the critical error but I cannot upload or select an an image. No errors apparent.

**Comment by meetmandeep** [comment]
@scottw12 We're aware of Live Slider image issue. All Mandeeps.com modules will get an update along with Vanjaro Release Candidate.
