### ISSUE TITLE
Cannot Delete Fonts

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1805]
**Product & Version**
V1.1.0
**Describe the bug**
Went to Menu->Design->Themes->Basic->Settings->Custom->gear(settings)->Fonts
Deleted several fonts. 
Saved the theme
Restarted from the Vanjaro menu.
Fonts now do not show up in Theme Builder Custom->Fonts.
However they are still all available to choose.

**Comment by Gaganbird** [comment]
I can confirm the issue will be fixed in the next upcoming release. In the meantime, you can follow the steps mentioned in https://github.com/vanjarosoftware/Vanjaro.Platform/discussions/1328
