### ISSUE TITLE
Porto Megamenu module breaks

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#1811]
**Product & Version**
Vanjaro Business v1.2.0 on DNN v9.10.1 with Porto v6.0.0

**Describe the bug**
After install of Vanjaro Business v1.2.0, a DNN page with the Porto Mega Menu module on it fails to fully load. The URL on page load says  "error=The+EnablePartialRendering+property+cannot+be+changed+after+the+Init+event." The mega menu still displays as expected, it's just the module that crashes the page. A mega menu on the page displays as expected.

**To Reproduce**
1. Create a DNN page on a Vanjaro Business site
2. Place a Porto Mega Menu module onto the DNN page
3. refresh the page and the error should be thrown and the page will fail load any module content

**Comment by eswanzey** [comment]
I should point out that the module in this case was using a Menu Style of Custom Menu.

**Comment by Gaganbird** [comment]
I can confirm the issue. We are investing it and will update you shortly.

**Comment by Tychodewaard** [comment]
@eswanzey what is Vanjaro Business?

**Comment by meetmandeep** [comment]
> @eswanzey what is Vanjaro Business?

It's the self-hosted, commercially supported version of Vanjaro: https://www.vanjaro.com/pricing

**Comment by Gaganbird** [comment]
We are still working on it and will provide you the build as soon as possible.
