### ISSUE TITLE
Ability to add a URL as a video source

### ISSUE THREAD

**Issue by tharris9d** [vanjarosoftware/Vanjaro.Platform#1836]
Vanjaro 1.1 Video block allows for a link to a video on the portal or from YouTube and works great. However we have our videos on a separate video server that has a unique https:// link to the video. We tried using it in the HTML5 source/link but it didn't work.

Any tips on getting it work? If not please add it to the list of feature requests.

Thanks, 
Tom

**Comment by meetmandeep** [comment]
@tharris9d Can you provide a sample URL that is not working with video block?

**Comment by tharris9d** [comment]
I got it working. I had a bad url. Thanks
