### ISSUE TITLE
Feature Request: limit the features of UX Manager

### ISSUE THREAD

**Issue by denisjoconnor** [vanjarosoftware/Vanjaro.Platform#185]
Currently there is no way to limit the features of UX Manager; Would it be possible to restrict the number of blocks shown as well as whether to show the styling tab or not.

For example, content editors may only need to make text/link changes to the Heading/Text/Button blocks while hiding the 'Styling' tab and some of the other 'Options' like font size and alignment etc.

**Comment by meetmandeep** [comment]
@denisjoconnor Can you please share your use case? It would help us define requirements in detail.

**Comment by denisjoconnor** [comment]
We're working on a use case currently but concerned giving a client access to most of the UX Manager will be risky. We ideally would not allow client/content editor access to anything in the below screenshot (tools for building pages, building content blocks, and adjusting the layout of content blocks)
![image](https://user-images.githubusercontent.com/16110075/97468079-c93ecb80-193c-11eb-862f-64ff37943b50.png)

Additionally we would not want to give them access to any of the below options (in blue) within a content block either
![image](https://user-images.githubusercontent.com/16110075/97468190-e8d5f400-193c-11eb-932f-e509b4619b47.png)

As well as anything in the below screenshot
![image](https://user-images.githubusercontent.com/16110075/97468245-f7241000-193c-11eb-8620-bd664e3489e3.png)

The only tools we ideally would like to give a client/content editor access to are the grey tools below (excluding the paintbrush)
![image](https://user-images.githubusercontent.com/16110075/97468353-158a0b80-193d-11eb-98c9-ccbbbca65930.png)

For ourselves all these tools are great and if there was a way to have role based functionality on the UX Manager where if a certain role was assigned you could limit the UX Manager to text, hyperlink, image changes only then that would be a rough use case, hope this helps explain! Thanks

**Comment by meetmandeep** [comment]
How do you address this in DNN? In DNN, Persona Bar will appear if a user is admin or has Edit access to the page. It works the same way in Vanjaro. If you don't want UX Manager then simply ensure that the user does not have admin or page edit rights. 

In DNN, you would grant the user access to individual module to edit an HTML Module. You may do the same in Vanjaro; that is grant them access to edit an individual module (app). You may use any DNN app for content building such as 2sxc / OpenContent and so forth. 

UX Mananger will only appear if the user has the rights to edit the page.

**Comment by denisjoconnor** [comment]
We currently use our own custom built content blocks which limit the amount of content a client can edit as well as using other third party content building modules like 2sxc. 

If we grant content editors access to individual modules in Vanjaro it won't help us as it is the Vanjaro 'custom blocks' that we want to allow our clients to edit while currently these are not appearing on the Vanjaro pages as DNN modules?

If we remove admin access it hides UX Manager but with standard DNN it keeps Persona bar only removes additional functionality that a specific user does not have privileges for i.e content editor can select existing module (created by us) and edit only certain fields (see below screenshot from one of our custom modules)

![image](https://user-images.githubusercontent.com/16110075/97552338-0aca8780-19cc-11eb-8fc3-7ba7ebb8ee8d.png)
![image](https://user-images.githubusercontent.com/16110075/97552498-3e0d1680-19cc-11eb-96dc-8474f4929641.png)

![image](https://user-images.githubusercontent.com/16110075/97552725-875d6600-19cc-11eb-9288-cee2ee02b4b1.png)

**Comment by meetmandeep** [comment]
There are no plans at the moment to allow individuals to only edit individual blocks on a page. If you must have that a specific user can only edit part of the page then continue to use 3rd party apps such as 2scx or any other DNN module.
