### ISSUE TITLE
Unable to remove role in page permissions

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#1905]
**Product & Version**
VP 1.2.0 / VB 1.2.1

**Describe the bug**
Once a role is added to the permissions grid, there's no way to remove it again

![2021-11-10_7-25-22](https://user-images.githubusercontent.com/8103212/141113957-ad82188c-0e79-48cd-b8ff-746ed1f878b1.jpg)
.

**Comment by meetmandeep** [comment]
@eswanzey If you uncheck both "View Tab" and "Edit Tab" and update, does it not remove it for you?

**Comment by eswanzey** [comment]
Oh, nice!
