### ISSUE TITLE
Disable page setting

### ISSUE THREAD

**Issue by aloscher** [vanjarosoftware/Vanjaro.Platform#1910]
I cannot find where you can disable a page so it becomes a placeholder for a submenu as I can do in DNN.

**Comment by meetmandeep** [comment]
Use the "Folder" option when creating a new page. Are you trying to change an existing page to placeholder? At this time, there is no option to change an existing page to Folder or vice a versa. 

![image](https://user-images.githubusercontent.com/29958123/142805949-822b7297-318c-4d12-acb8-be998b311e9a.png)
