### ISSUE TITLE
Edit mode not loading

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#1911]
**Product & Version**
1.2

**Describe the bug**
I have a setup with 2 languages.
Website.com is connected to en-us and website.nl is connected (redirect) to .com/nl-nl
If I login to .com and start editing, all is well. If I switch the language to nl (.com/nl-nl) it also works.
If I login to website.nl, the edit mode is not loading.

**Expected behavior**
Is I login to the website.nl I can also edit the website.

**Screenshots**
![image](https://user-images.githubusercontent.com/9091997/142173350-b5710ab9-d504-47a1-b95c-d98fe4a4c0da.png)

**Additional context**
Add any other context about the problem here including the Browser/OS version.

**Comment by ashishpachauriap** [comment]
Can you please provide a screencast of the issue.

**Comment by scottw12** [comment]
Same Issue I am having on my homepage I can log in and as soon as I click to open the Vanjaro menu an overlay covers my screen and I cannot do a thing.  I can open the menu on any other page but the home page just opens the overlay and hangs there. 

 screen cast: http://somup.com/crXvr90uG8
Error log:
Navigated to https://dev.jcesba.org/
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. dev.jcesba.org
Some cookies are misusing the recommended “SameSite“ attribute 12
GEThttps://dev.jcesba.org/admin/menus/ModuleActions/ModuleActions.js?cdv=107
[HTTP/1.1 404 Not Found 430ms]

Source map error: Error: request failed with status 404
Resource URL: https://dev.jcesba.org/DesktopModules/Vanjaro/Common/Frameworks/Toastr/2.1.4/js/toastr.min.js?cdv=107
Source Map URL: toastr.js.map
GEThttps://dev.jcesba.org/admin/menus/ModuleActions/ModuleActions.js?cdv=107
[HTTP/1.1 404 Not Found 19ms]

Loading failed for the <script> with source “https://dev.jcesba.org/admin/menus/ModuleActions/ModuleActions.js?cdv=107”. dev.jcesba.org:182:1
Source map error: Error: request failed with status 404
Resource URL: https://dev.jcesba.org/DesktopModules/Vanjaro/Common/Frameworks/Bootstrap/5.0.0/js/bootstrap.bundle.min.js?cdv=107
Source Map URL: bootstrap.bundle.min.js.map
Uncaught TypeError: can't access property "refresh", VjEditor is null
    GrapesjsInit https://dev.jcesba.org/DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/uxmanager.min.js?cdv=107:20
    jQuery 10
    GrapesjsInit https://dev.jcesba.org/DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/uxmanager.min.js?cdv=107:20
    <anonymous> https://dev.jcesba.org/:172
    jQuery 13
uxmanager.min.js:20:114358
Uncaught TypeError: n.front is not a function
    create https://dev.jcesba.org/DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/uxmanager.min.js?cdv=107:20
    success https://dev.jcesba.org/DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/uxmanager.min.js?cdv=107:20
    jQuery 7
    GrapesjsInit https://dev.jcesba.org/DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/uxmanager.min.js?cdv=107:20
    <anonymous> https://dev.jcesba.org/:172
    jQuery 13
uxmanager.min.js:20:35740
Source map error: Error: request failed with status 404
Resource URL: https://dev.jcesba.org/DesktopModules/Vanjaro/Common/Frameworks/Bootstrap/5.0.0/css/bootstrap.min.css
Source Map URL: bootstrap.min.css.map

http://somup.com/crXvr90uG8

**Comment by Tychodewaard** [comment]
@ashishpachauriap If the video of Scott was not enough, I explained a similar example on https://www.youtube.com/watch?v=f5hL9ftdUrI

**Comment by Tychodewaard** [comment]
I also tried to tie both languages to the same domain as a primary.
In that case, I still get the language switch:
![image](https://user-images.githubusercontent.com/9091997/157309452-ff62d029-3567-4242-be28-c25c88a29015.png)

But if I switch to edit mode, the url says NL but the content switches to EN
![image](https://user-images.githubusercontent.com/9091997/157309633-853bb676-c76a-4e9d-a3b7-962d014185c4.png)

**Comment by Tychodewaard** [comment]
@narensingh008 Is there a way to have a workaround until this issue has been fixed and released? Or something in the database I can change? Because at this point I have sites that can not be edited.

**Comment by narensingh008** [comment]
We are not able to find any workaround, we have added the issue in issues list and will try to fix this in upcoming release.

**Comment by Tychodewaard** [comment]
Ok, couple of things:
Is there any idea what the cause is?
Is there any idea when that release will be? This is important as the customer has not been able to edit the content.


________________________________
Van: Naren Singh ***@***.***>
Verzonden: Monday, March 14, 2022 8:14:10 AM
Aan: vanjarosoftware/Vanjaro.Platform ***@***.***>
CC: Tycho de Waard ***@***.***>; Author ***@***.***>
Onderwerp: Re: [vanjarosoftware/Vanjaro.Platform] Edit mode not loading (Issue #1911)


We are not able to find any workaround, we have added the issue in issues list and will try to fix this in upcoming release.

**Comment by hshimanshusharma** [comment]
`Is there any idea what the cause is?`
Its caused by internal code and cannot fix with database changes.

**Comment by hshimanshusharma** [comment]
Is there any idea when that release will be?
Maybe between two to three week

**Comment by Tychodewaard** [comment]
Please reopen. This issue is not fixed in 1.4

**Comment by Tychodewaard** [comment]
It was partially fixed. If you have a ML setup and set to forward, things are well.
If you have the setup canonical, the issue persists.
