### ISSUE TITLE
ENTER Key behavior

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#1919]
**Product & Version**
VB 1.2.1

**Describe the bug**
Executing a Search with the ENTER key causes Vanjaro display to go blank.

**To Reproduce**
1. Go to Tools - Extensions & Plugins
2. Enter a string of characters in the Search box in the left-hand column and click the ENTER key
3. See how the main Vanjaro display goes blank.

**Expected behavior**
Typical response after pressing the ENTER key on a search query is to receive a visual acknowledgement in the UI.

**Current behavior**
The Vanjaro left-hand column goes blank.

**Comment by Gaganbird** [comment]
@eswanzey Thanks for reporting this.
