### ISSUE TITLE
Colors not persisting

### ISSUE THREAD

**Issue by jasonsutter87** [vanjarosoftware/Vanjaro.Platform#1924]
**Product & Version**
Vanjaro Platform 1.2.0
DNN Platform 09.10.02 (0)

**Describe the bug**
Site SCSS colors not persisting

**To Reproduce**
1.  menu -> design -> themes -> site -> basic ->  Site Section "Color"
2. Changing the colors
3. Selecting publish

"site setting saved"

**Expected behavior**
expected to see colors changes. yet the defaults stay

**Comment by ashishpachauriap** [comment]
It seems that you are clicking on publish button of the page instead of saving theme.
Please make sure you are saving the theme after the changes.
See image
![ThemeSave](https://user-images.githubusercontent.com/42379850/142970520-5a8037fd-fc99-4a61-87ae-a47898974908.png)
