### ISSUE TITLE
URL starts with padding 5 and keeps resetting padding back to 5

### ISSUE THREAD

**Issue by paulfijma** [vanjarosoftware/Vanjaro.Platform#193]
For every line in a text block where I add an URL, I have to set padding to zero to keep in line with the rest of the text. 
Every time I edit the text, the padding for the URL goes back to 5. It changes the line spacing and makes my lines look unevenly spaced.

**Comment by meetmandeep** [comment]
@paulfijma Can you provide a screenshot so we can better understand the issue?

**Comment by paulfijma** [comment]
I made the screenshots:
ORIGINAL
![msedge_nzhqHASJZQ](https://user-images.githubusercontent.com/38673029/95655710-88a41d00-0b09-11eb-9980-415eec2cd944.png)
EDIT
![msedge_Xhe579UIED](https://user-images.githubusercontent.com/38673029/95655717-8e99fe00-0b09-11eb-9524-73b307539ded.png)

i have to add:
reproduce: 
go to an page to edit, edit a text block and add a URL by selecting a text and make it an URL. it adds the 5 points padding.
to make it as i like i remove the padding. then publish the text. (all looks as intend).
open the page again for editing and add a URL. (as soon as you add the URL the previous expands also the padding. 

When i publish the page, the published page looks as intended without the padding.  (although i didn't remove the padding for the second added URL...) so it pads or pads not. (so it is inconsistent behaviour... making editing a little more work. )

the same textbox in edit mode and previes shows the difference:
![image](https://user-images.githubusercontent.com/38673029/95655959-4aa7f880-0b0b-11eb-801d-33de11aa26f3.png)
