### ISSUE TITLE
Can't select Folder-type page within Menu settings

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#2020]
**Product & Version**
Vanjaro for DNN 1.2.0 

**Describe the bug**
When selecting the root page in the Menu settings, Folder items (and their children) aren't available to choose from in the dropdown selector.

**To Reproduce**
1. Create a Folder page type with one or more child pages
2. Add a Menu block to the page and set the Root Page to "Individual Page"
3. In the dropdown selector, notice how Folder pages and their children aren't available to choose from

**Expected behavior**
The Folder and child pages should be available to choose from in setting the root page of a menu.

**Comment by hshimanshusharma** [comment]
We have duplicated the issue and logged it to resolve it in the next update
