### ISSUE TITLE
Button set to DNN page link doesn't work

### ISSUE THREAD

**Issue by puresystems** [vanjarosoftware/Vanjaro.Platform#2042]
**Product & Version**
DNN Module v1.2.0, DNN v9.10.1

**Describe the bug**
Button set to link to a DNN page doesn't create the proper link, and instead appears to set the link to html from a page.

**To Reproduce**
1. Go to a vanjaro page, add a Button element via the Blocks section
2. Click on the button and in the button options panel, select the Page link icon to display a drop-down of DNN page
3. Select a Page from the drop-down
4. Click Publish and test the button.

**Expected behavior**
The URL in the button href is set to the url of the page selected

**Current behavior**
The href contains the HTML from the selected page instead of the url.

**Comment by mksmanish79** [comment]
The page you are linking to is redirect page?

**Comment by puresystems** [comment]
Ah, yes i see that it was a redirected page, tested with a normal page and it works OK.
