### ISSUE TITLE
Install as DNN Module

### ISSUE THREAD

**Issue by wbonekamp** [vanjarosoftware/Vanjaro.Platform#208]
Installed Vanjaro version 0.5.2. on DNN 972. 
I can't add it to a page... I can see it's installed as library but not as module.
How do I add the module to a page?

![image](https://user-images.githubusercontent.com/7567981/95968546-da9cb980-0e0d-11eb-8ef0-d0ac4a63862e.png)

**Comment by Tychodewaard** [comment]
You don't add it to a page.
In the persona bar there is an option Vanjaro in the manage section.

**Comment by wbonekamp** [comment]
Thanks Tycho!

So you can't use it as a block module on a page?
I would like to use with my own skin/theme... but I assume that's not possible at the moment?

**Comment by Tychodewaard** [comment]
That's correct. And it is not meant for that, either. 
It is a tool/platform that allows you to develop your own themes and manage pages/content in a very easy way.

Although it looks like a Persona bar on steroids, it is completely different.

**Comment by wbonekamp** [comment]
Did you already create websites with vanjaro? do you have a showcase?

**Comment by Tychodewaard** [comment]
nope, just testing.
But https://www.youtube.com/c/VanjaroSoftware/videos gives lots of examples

**Comment by wbonekamp** [comment]
I noticed but I need some showcase websites (urls) build by Vanjaro.

Customer need to know what you can do with the theme builder.
They like to know if it's better than Weebly/Duda/Wix

**Comment by Tychodewaard** [comment]
It is 'better' than the ones mentioned if you are looking for freedom and options. If you are the kind of person that is overwhelmed easily, it might be too much.

So, it is better:
- options. I think you could compare the options to Webflow. It is a lot. Except in the end you have a real website instead of a static
- you can extend. It leverages all of DNN and all other extensions.

**Comment by wbonekamp** [comment]
Yes we really like the option to also use the other DNN extensions. It's best of both worlds!

Hopefully many DNN users will use Vanjaro.. it has a lot of potential.

**Comment by meetmandeep** [comment]
@wbonekamp Please take a look at this video to get started with Vanjaro for DNN: https://www.youtube.com/watch?v=CjBhaWPvxh8
