### ISSUE TITLE
An element with the ID layer-manager

### ISSUE THREAD

**Issue by mastercodefu** [vanjarosoftware/Vanjaro.Platform#2104]
An element with the ID layer-manager already exists in the document.
![image](https://user-images.githubusercontent.com/9981099/154798546-6b766616-3f65-413d-9076-2e6cbf5abd51.png)

Any ideas
Craig

**Comment by Gaganbird** [comment]
It was known issue and was fixed in one of the previous releases. Make sure you are using  latest version (1.3.0)
