### ISSUE TITLE
when searching through assets, a persistent query would save a lot of time

### ISSUE THREAD

**Issue by mksmanish79** [vanjarosoftware/Vanjaro.Platform#2110]
### Discussed in https://github.com/vanjarosoftware/Vanjaro.Platform/discussions/2107

<div type='discussions-op-text'>

<sup>Originally posted by **eswanzey** February 22, 2022</sup>
when selecting an image or asset, the search query entered in the search field doesn't persist when selecting a different directory to search in - the query field gets cleared. It would be great if the query could persist when selecting different folders to look in!</div>

**Comment by nikhilmandeeps** [comment]
Close #2189
