### ISSUE TITLE
Can not create or migrate to a Vanjaro page on portals

### ISSUE THREAD

**Issue by JohnK74** [vanjarosoftware/Vanjaro.Platform#2114]
DNN 9.10.1
Vanjaro for DNN 1.3.0

I can only create /migrate a Vanjaro page on the parent site.
After creating a new portal, Vanjaro can't create or migrate a new page

Create a clean install of DNN 9.10
Install Vanjaro 1.3
Manage Settings - Click Vanjaro - click either "Create" or "Migrate"
New page creates successfully

Add a new Portal 
Manage Settings - Click Vanjaro - click either "Create" or "Migrate"
Empty page with spinning icon in the center  - stays in a loop

On inspection - error message is:
false?skinsrc=[g]skins/vanjaro/base&containersrc=[g]containers/vanjaro/base:1 
        
       Access to XMLHttpRequest at 'https://www.sfsf.org/api/vanjaro/page/get?_=1645657126459' from origin 'https://sfsf.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by hshimanshusharma** [comment]
@JohnK74 

This issue has been duplicated and resolved
```
On inspection - error message is:
false?skinsrc=[g]skins/vanjaro/base&containersrc=[g]containers/vanjaro/base:1
```

And, Unable to duplicate empty page with spinning icon stay in a loop
