### ISSUE TITLE
on conversion, convert h1-h6 to header block of same type

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#2133]
**Is your feature request related to a problem? Please describe.**
anything that's h1-h6 currently gets converted to a text block. it takes several steps to then turn it into a header block 

**Describe the solution you'd like**
in the conversion process, convert anything that is currently an h1-h6 into a header block of the same type

**Comment by ishitagupta94** [comment]
Thanks for reporting this.
