### ISSUE TITLE
Carousel doesn't like more than 5 images

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#2166]
**Product & Version**
Vanjaro Platform 1.3.0

**Describe the bug**
I added 8 images to a carousel. They seem to be correct when viewed in the editor, but when published and viewed with the Vanjaro panel closed, it breaks after advancing past carousel item #5 whereby the next/back fails to work and some images are missing in the display.

An error gets thrown to the console - "Failed to load resource: the server responded with a status of 404 ()" - it references the file  /worker.js

After a few seconds, an additional error appears in the console:

Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at Z._setActiveIndicatorElement (js:15:13927)
    at Z._slide (js:15:15131)
    at Z.next (js:15:10734)
    at Z.nextWhenVisible (js:15:10803)

**To Reproduce**
Add a Carousel block and place 6 or more images into it. Publish it, and then try and navigate to all slides. Notice how it works correctly up to slide #5, then breaks after that.

**Comment by Gaganbird** [comment]
Thanks for reporting this.
