### ISSUE TITLE
Custom font not saved

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#222]
I added Lato as a font.
Font family: 'Lato', sans-serif;
Font CSS:
@import url('https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap');

Then I go to designer - Themes - basic - - menu - navigation and I change the font to Lato.
After saving, I get:
Theme
Error: Invalid CSS after "...o', sans-serif;": expected "}", was "!important;" on line 629:34 of C:/Inetpub/vhosts/schutte.nl/httpdocs/Portals/_default/vThemes/Basic/scss/Bootstrap/ >> font-family: 'Lato', sans-serif;!important; ---------------------------------^

**Comment by Tychodewaard** [comment]
Related to #346 ?

**Comment by mksmanish79** [comment]
Lato
'Lato', sans-serif
@import url('https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap');

remove semicolon after sans-serif in Font family and it will work.
