### ISSUE TITLE
DNN 9.11 compatibility?

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#2274]
Running Vanjaro 1.4 on DNN 9.10.1, I just tried to upgrade to 9.11 but this fails.
Can you confirm that this is happening? Or should this work? 

**Expected behavior**
After install/upgradewizard.aspx, I get a working website 

**Current behavior**
After install/upgradewizard.aspx, I keep being redirected to install/upgradewizard.aspx which then gives a 404. The upgrade proces took 7 seconds and the database still says it is 9.10.1

![image](https://user-images.githubusercontent.com/9091997/193896431-74962c03-b992-47e4-8f0f-f2e821d321a1.png)

**Comment by Gaganbird** [comment]
It is working fine for me. You can see if any error logged in \Portals\_default\Logs\
