### ISSUE TITLE
LICENSING ISSUE

### ISSUE THREAD

**Issue by igorssl** [vanjarosoftware/Vanjaro.Platform#2319]
Vanjaro for DNN: version 1.4.0
DNN: version 9.11.2

I had tried out the Premium theme, but let the trial expire as we were not ready to purchase yet.
Now I'm getting a red screen (/DesktopModules/Vanjaro/Store/Licensing/Views/Error.aspx) with "LICENSING ISSUE Looks like VanjaroAppLicense key is missing in web.config" when I try to go to any Vanjaro enabled page.

**Comment by meetmandeep** [comment]
Licensed Vanjaro Extensions require the following in web.config for licensing to work properly. It seems like the following has been removed from your web.config, <system.webServer>, <modules>

      <add name="VanjaroAppLicense" type="Vanjaro.AppStore.Licensing.Components.HttpModule,Vanjaro.AppStore.Licensing" preCondition="managedHandler" />

**Comment by igorssl** [comment]
Interesting. I have not removed it directly except maybe it was removed when I uninstalled and re-installed Vanjaro.

After adding it back in I cannot do any work on the site because it constantly pops up the Licensing tab asking me to Activate the expired Premium that we were testing on a trial and are not ready to purchase yet. Any way to stop that?

**Comment by meetmandeep** [comment]
You would need to activate the premium theme to continue since the trial has expired. You could try switching to Basic theme (from direct database query) as a workaround.

**Comment by igorssl** [comment]
So are you saying that you are forcing clients to pay even if they decide to not continue after the trial? That's a very underhanded thing to do!

You need to have an easy way of backing out without having to do a database query.

While you are fixing that, could you provide the query to fix the infinite loop I'm in right now?

**Comment by meetmandeep** [comment]
Licensed extensions are available for 14 day trial. Once the trial expires, the extensions stops working and you're welcome to uninstall it. The only exception is Premium Theme; which is not merely an app but the foundation/framework to build the site on. It's recommended to switch over to basic theme prior to the expiration of the trial. Once it expires, you have the following options: 

- Activate Premium Theme
- Restore From Backup 
- Manually switch over to Basic Theme using the instructions provided below

**To manually switch over to Basic Theme**

Execute the following SQL Query directly against the Database via SQL Management Studio or other tool:

`Update VJ_Core_Setting set Value= 'Basic' where Name = 'Theme'`

Be sure to delete Vanjaro.Themes.Premium.dll from /bin folder and restart IIS App Pool to clear cache.

**Comment by igorssl** [comment]
Thank you, that helped.

Having this info at the time of installation would have been helpful.
