### ISSUE TITLE
PersonaBar -> Manage -> Vanjaro only visible to superadmins

### ISSUE THREAD

**Issue by igorssl** [vanjarosoftware/Vanjaro.Platform#2320]
Vanjaro for DNN: version 1.4.0
DNN: version 9.11.2

PersonaBar -> Manage -> Vanjaro is only visible to superadmins. A site user in the administrator role does not see that item and has no way of converting an existing page to Vanjaro.

**Comment by Gaganbird** [comment]
By default it is visible to superuser. You can run the following SQL query to make it visible to admin also.

insert into PersonaBarMenuPermission values (0, (select MenuId from PersonaBarMenu where Identifier = 'Vanjaro'), 1, 1, 0, null, 1, GETDATE(),1, GETDATE())
