### ISSUE TITLE
Background Images not working from Styling Tab

### ISSUE THREAD

**Issue by joshgk00** [vanjarosoftware/Vanjaro.Platform#24]
I added a grid with 2 columns. When I tried to apply a background image to one of the columns the image didn't show up. Here's a screencast of what I did.
https://www.screencast.com/t/Rvy5GFZ911y

**Comment by meetmandeep** [comment]
I'm able to confirm this issue. Background Images not working in Styling Tab

**Comment by meetmandeep** [comment]
This has been fixed.
