### ISSUE TITLE
Unable to Install Extension: DNN 9.7

### ISSUE THREAD

**Issue by 50Bubbles** [vanjarosoftware/Vanjaro.Platform#256]
StartJob Reading files

Info File apps-about-resources.zip read successfully

Info File apps-icon-resources.zip read successfully

Info File apps-image-resources.zip read successfully

Info File apps-link-resources.zip read successfully

Info File apps-modulesettings-resources.zip read successfully

Info File apps-video-resources.zip read successfully

Info File AuthenticationViews/App_LocalResources\Login.ascx.resx read successfully

Info File AuthenticationViews\Login.ascx read successfully

Info File AuthenticationViews\Login.ascx.cs read successfully

Info File AuthenticationViews\Login.ascx.designer.cs read successfully

Info File AuthenticationViews\Settings.ascx read successfully

Info File AuthenticationViews\Settings.ascx.cs read successfully

Info File AuthenticationViews\Settings.ascx.designer.cs read successfully

Info File bin\AdvancedStringBuilder.dll read successfully

Info File bin\HtmlAgilityPack.dll read successfully

Info File bin\ImageProcessor.dll read successfully

Info File bin\ImageProcessor.Plugins.WebP.dll read successfully

Info File bin\LibSassHost.dll read successfully

Info File bin\Mandeeps.DNN.Modules.Licensing.dll read successfully

Info File bin\System.Buffers.dll read successfully

Info File bin\Vanjaro.Common.dll read successfully

Info File bin\Vanjaro.Container.dll read successfully

Info File bin\Vanjaro.Core.dll read successfully

Info File bin\Vanjaro.Core.Extensions.Notification.Notification.dll read successfully

Info File bin\Vanjaro.Core.Extensions.Workflow.Review.dll read successfully

Info File bin\Vanjaro.Core.Providers.Authentication.dll read successfully

Info File bin\Vanjaro.Migrate.dll read successfully

Info File bin\Vanjaro.Skin.dll read successfully

Info File bin\Vanjaro.URL.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Apps.About.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Apps.Icon.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Apps.Image.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Apps.Link.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Apps.LogsSettings.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Apps.ModuleSettings.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Apps.ThemeBuilder.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Apps.Video.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Block.BlockLanguage.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Block.BreadCrumb.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Block.Custom.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Block.Login.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Block.LoginLink.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Block.Logo.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Block.Menu.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Block.Profile.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Block.Register.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Block.RegisterLink.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Block.SearchInput.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Block.SearchResult.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Assets.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Azure.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.CustomCSS.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Domain.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.EmailServiceProvider.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Extensions.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.GoogleAnalytics.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Help.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Languages.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.LogoAndTitle.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Logs.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.MemberProfile.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Pages.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Pixabay.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Privacy.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Roles.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Scheduler.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Security.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.SEO.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.SiteGroups.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Sites.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.SQLConsole.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Theme.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Users.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.Workflow.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Menu.YouTube.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Toolbar.DeviceMode.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Toolbar.Fullscreen.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Toolbar.Language.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Toolbar.Navigator.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Toolbar.PageSetting.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Toolbar.Preview.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Toolbar.Redo.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Toolbar.Undo.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Toolbar.VersionManagement.dll read successfully

Info File bin\Vanjaro.UXManager.Extensions.Toolbar.ViewLayout.dll read successfully

Info File bin\Vanjaro.UXManager.Library.dll read successfully

Info File block-breadcrumb-resources.zip read successfully

Info File block-custom-resources.zip read successfully

Info File block-language-resources.zip read successfully

Info File block-login-resources.zip read successfully

Info File block-loginlink-resources.zip read successfully

Info File block-logo-resources.zip read successfully

Info File block-menu-resources.zip read successfully

Info File block-profile-resources.zip read successfully

Info File block-register-resources.zip read successfully

Info File block-registerlink-resources.zip read successfully

Info File block-searchinput-resources.zip read successfully

Info File block-searchresult-resources.zip read successfully

Info File common-library-resources.zip read successfully

Info File container-resource.zip read successfully

Info File core-extensions-notification-resources.zip read successfully

Info File core-extensions-review-resources.zip read successfully

Info File core-library-resources.zip read successfully

Info File Install\Common.01.00.00.SqlDataProvider read successfully

Info File Install\Core.01.00.00.SqlDataProvider read successfully

Info File Install\Core.01.00.01.SqlDataProvider read successfully

Info File Install\Core.01.00.02.SqlDataProvider read successfully

Info File Install\Migrate.01.00.00.SqlDataProvider read successfully

Info File Install\Migrate.Uninstall.SqlDataProvider read successfully

Info File Install\Uninstall.Common.SqlDataProvider read successfully

Info File Install\Uninstall.Core.SqlDataProvider read successfully

Info File Install\Uninstall.Migrate.SqlDataProvider read successfully

Info File Install\Uninstall.URL.SqlDataProvider read successfully

Info File Install\URL.01.00.00.SqlDataProvider read successfully

Info File Install\URL.Uninstall.SqlDataProvider read successfully

Info File Install\URL.xml read successfully

Info File library-uxmanager-resources.zip read successfully

Info File License.txt read successfully

Info File licenses-resources.zip read successfully

Info File menu-assest-resources.zip read successfully

Info File menu-customecss-resources.zip read successfully

Info File menu-domain-resources.zip read successfully

Info File menu-extensions-resources.zip read successfully

Info File menu-help-resources.zip read successfully

Info File menu-integrations-azure-resources.zip read successfully

Info File menu-integrations-emailserviceprovider-resources.zip read successfully

Info File menu-integrations-googleanalytics-resources.zip read successfully

Info File menu-integrations-pixabay-resources.zip read successfully

Info File menu-integrations-youtube-resources.zip read successfully

Info File menu-languages-resources.zip read successfully

Info File menu-logoandtitle-resources.zip read successfully

Info File menu-logs-resources.zip read successfully

Info File menu-logssettings-resources.zip read successfully

Info File menu-memberprofile-resources.zip read successfully

Info File menu-pages-resources.zip read successfully

Info File menu-privacy-resources.zip read successfully

Info File menu-roles-resources.zip read successfully

Info File menu-scheduler-resources.zip read successfully

Info File menu-security-resources.zip read successfully

Info File menu-seo-resources.zip read successfully

Info File menu-sitegroups-resources.zip read successfully

Info File menu-sites-resources.zip read successfully

Info File menu-sqlconsole-resources.zip read successfully

Info File menu-theme-resources.zip read successfully

Info File menu-themebuilder-resources.zip read successfully

Info File menu-users-resources.zip read successfully

Info File menu-workflow-resources.zip read successfully

Info File migrate-vanjaro.zip read successfully

Info File bin\libsass.dll read successfully

Info File providers-authentication-resources.zip read successfully

Info File Release.txt read successfully

Info File skin-resource.zip read successfully

Info File themes-resources.zip read successfully

Info File toolbar-devicemode-resources.zip read successfully

Info File toolbar-fullscreen-resources.zip read successfully

Info File toolbar-language-resources.zip read successfully

Info File toolbar-navigator-resources.zip read successfully

Info File toolbar-pagesetting-resources.zip read successfully

Info File toolbar-preview-resources.zip read successfully

Info File toolbar-redo-resources.zip read successfully

Info File toolbar-undo-resources.zip read successfully

Info File toolbar-versionmanagement-resources.zip read successfully

Info File toolbar-viewlayout-resources.zip read successfully

Info File url-resources.zip read successfully

Info File Vanjaro.dnn read successfully

EndJob Reading files done.

StartJob Reading Installation Manifest file

Info Reading Package Manifest - Library - Vanjaro

Failure Install aborted - The module being installed is not compatible with this version of DNN. An upgrade to version 9.7.2 is required.

**Comment by mksmanish79** [comment]
You need to first upgrade your DNN version to 9.7.2 and install vanjaro latest extension after that. 
Download DNN 9.7.2 upgrade from https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.7.2 and follow this https://dnndocs.com/content/getting-started/setup/upgrades/index.html
