### ISSUE TITLE
Source code to public repo

### ISSUE THREAD

**Issue by kurtwilbies** [vanjarosoftware/Vanjaro.Platform#27]
When will the source become accessible for both the developers and testers?

**Comment by meetmandeep** [comment]
Source code will be available along with BETA release. Refer to Vanjaro.com for a timeline. 

Our current focus is on Alpha 3: Standalone Vanjaro Extension that can be installed on existing DNN Sites along with migration functionality. 

We'll release the source code along with development tutorials and templates with BETA release.
