### ISSUE TITLE
Module settings not available through persona bar  

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#275]
I want to display a module title of an EasyDNNNews module or widget. (And set the h2)
As this can not be done (AFAIK) in Vanjaro (yet?), I go to the page settings in the Persona bar en hit the settings icon of the module.
This launches an empty popup.

**Comment by meetmandeep** [comment]
Vanjaro will not support displaying the "Module Title" option. You can simply drag a Headline block and use that as heading. You can set any Heading Tag (H1 to H6), set colors, font size, and so forth. 

There are 10 style to choose from as well. In next version (0.5.3), there will be option to customize these styles from Theme Editor.

**Comment by Tychodewaard** [comment]
Ok, that will do. At least for now :-) There might be usecases in the future where one would like to display a module title. But I'll create new one if that is the case and I can explain more in detail.
