### ISSUE TITLE
Alpha 3

### ISSUE THREAD

**Issue by igor-bizi** [vanjarosoftware/Vanjaro.Platform#28]
Hi,
I tried to UL Alpha 3 ZIP Extension for DNN 9.5.0 and I got Error for ZIP file. I also updated max upload file size.
Best 
Igor
----------------------------------------------------
An unknown error has occured. Please check your installation zip file and try again.
Common issues with bad installation files:
Zip file size is too large, check your IIS settings for max upload file size.
Missing resources in the zip file.
Invalid files in the package.
File extension is not .zip.
Check that you are logged in.
------------------------------------------------

**Comment by mksmanish79** [comment]
Did you followed the steps as instructed in video https://youtu.be/CjBhaWPvxh8

**Comment by igor-bizi** [comment]
Yes I followed the steps. I even made a clean DNN 9.5.0 install.
![image](https://user-images.githubusercontent.com/65033041/81428124-1c894b80-915c-11ea-971b-7a18e77449c9.png)

**Comment by mksmanish79** [comment]
Please share View error log information.

**Comment by igor-bizi** [comment]
You have it in the first message bellow my name.

**Comment by igor-bizi** [comment]
I updated DNN to 9.6.0. and I got the same error.

**Comment by mksmanish79** [comment]
New to IIS7+ you must also specify the Max file upload size in the security section of the system.webServer section:

<system.webServer>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="100663296" />
      </requestFiltering>
    </security>
</system.webServer>

**Comment by igor-bizi** [comment]
Yes, THX. It is working now. I added the security section and also I increase max file size in the web.config file.
