### ISSUE TITLE
Sometimes sorting the pages opens blocks UI

### ISSUE THREAD

**Issue by Gaganbird** [vanjarosoftware/Vanjaro.Platform#288]
![image](https://user-images.githubusercontent.com/52308516/97978862-34344a80-1df4-11eb-9145-46116fd91a85.png)
![image](https://user-images.githubusercontent.com/52308516/97978987-6d6cba80-1df4-11eb-8617-e8b4ce3c66d8.png)

**Comment by hshimanshusharma** [comment]
@Gaganbird  the issue is not duplicating, maybe it's fixed confirm and close the issue
