### ISSUE TITLE
Unable to Publish Migrated Page

### ISSUE THREAD

**Issue by joshgk00** [vanjarosoftware/Vanjaro.Platform#29]
I installed Alpha 3 as an extension to a DNN 9.5 test site. I tried migrating a page that was already created. The content was migrated to Vanjaro as expected, but I was unable to click the Publish buttons at the bottom.  Looks like some html div was overlaying the button and not allowing me to click on them. Below is a screencast of what happened. The theme I had installed on the page was Polo by WebsitesCreative.

https://www.screencast.com/t/KJJkHFSPZKy

**Comment by meetmandeep** [comment]
That looks like a conflict with 2sxc. Can you confirm if the issue persists on other pages that does not have 2scx module?

**Comment by joshgk00** [comment]
I'll try that and let you know how it goes
________________________________
