### ISSUE TITLE
Custom font makes Vanjaro crash(?)

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#346]
I added Open sans as a custom font. 
After saving, Vanjaro seems to have trouble. 

![image](https://user-images.githubusercontent.com/9091997/100148967-c2549b80-2e9d-11eb-99ff-494044a1fbf0.png)

If I go back to the Theme - Basic - Custom I get a mix of Vanjaro and the persona bar
![image](https://user-images.githubusercontent.com/9091997/100149093-f4fe9400-2e9d-11eb-9aac-25270ee17b78.png)

**Comment by Tychodewaard** [comment]
Btw: if you have a solution/query to fix this, I would be very happy...

**Comment by joshgk00** [comment]
I'm also seeing this as well. Not sure how to fix this. It's a showstopper....

**Comment by Tychodewaard** [comment]
@meetmandeep Would a temp solution be possible to inject the Google Font code in the custom css module in the PersonaBar?

**Comment by meetmandeep** [comment]
> @meetmandeep Would a temp solution be possible to inject the Google Font code in the custom css module in the PersonaBar?

Yes. You may add your custom font via Custom CSS (under Settings which is same as Portal.css)

We'll get this issue escalated to see if there's a workaround until RC. Thanks

**Comment by Tychodewaard** [comment]
@joshgk00 (or others that stumble upon this issue) FYI: I just tested and indeed it works. If you go to the persona bar of DNN (if you can not find a page that is not Vanjaro, try /admin) and choose Settings-Custom CSS. For Montserrat I added the following:

@import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,600;1,400&display=swap');

h1, h2, h3, h4, h5, h6, p  {
font-family: 'Montserrat', sans-serif !important;
}

**Comment by meetmandeep** [comment]
Update. To duplicate the issue, be sure to check with both "Site" and "Custom" option in Theme Builder.

**Comment by meetmandeep** [comment]
@Tychodewaard Can you provide the exact CSS that you're using for the new font that causes a crash?

**Comment by joshgk00** [comment]
This is what crashed it for me
Open Sans
‘Open Sans’, san-serif

@import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap');

**Comment by meetmandeep** [comment]
Thanks @joshgk00 I'm able to reproduce this now.

**Comment by meetmandeep** [comment]
> @import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap');

The issue is due to the semi-colon within the URL such as (0,300;0). The semi-colon is breaking the current implementation of DNN's Client Resource Management (Minify CSS). 

The best way to move forward is to copy and paste the entire CSS rather than using the @import tag. This will also include performance benefits as the browser no longer has to download the CSS first. 

We'll update the video with new instructions. To avoid any confusion, @import tag will no longer allowed in Custom Font CSS.
