### ISSUE TITLE
Replacement tokens

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#349]
Is token replacement broken? I checked replcae tokens and I tested with  [Browser:Browser] and  [User:DisplayName] but that does not seem to work.

**Comment by joshgk00** [comment]
I've also experienced this not working as well.

**Comment by pankajmandeeps** [comment]
I am unable to duplicate the issue make sure Page Setting>Basic>Personalization>Replace Tokens setting is set to yes

**Comment by Tychodewaard** [comment]
I tested with a fresh install and can confirm that it works as expected. The DNN Sharp tokens (which should be the same behaviour according to Bogdan) do not work.

**Comment by meetmandeep** [comment]
We're just calling the DNN Platform Token Replace:

`new TokenReplace().ReplaceEnvironmentTokens(page.Content)`

Feel free to bring this to DNN Sharp attention and let us know if it needs to be any different.

**Comment by bogdan-litescu** [comment]
Can you check web.config that the TokenProvider is set to My Tokens?
There should be a line such as 
<tokens defaultProvider="MyTokensProvider">

**Comment by bogdan-litescu** [comment]
Further info about the new Token Provider is at https://github.com/dnnsoftware/Dnn.Platform/pull/3820

**Comment by bogdan-litescu** [comment]
Actually, I just checked with our development team, and the MyTokens provider will be available in the next Plant an App 1.11 release. We're aiming to release it this year.

**Comment by meetmandeep** [comment]
@Tychodewaard I'm closing this issue as there's nothing actionable on our end. As @bogdan-litescu mentioned, you need to update your web.config to swap out the default token provider with MyTokens provider.
