### ISSUE TITLE
Cannot load libwebp.dll

### ISSUE THREAD

**Issue by meetmandeep** [vanjarosoftware/Vanjaro.Platform#35]
Throws an error when attempting to upload an image via Asset Manager if MSVCR120.DLL is missing on the server.

**Comment by paulfijma** [comment]
hi mandeep, i have exactly this error when i upload images. The image is uploaded, but the upload process doesn't end (until i [X] it.  so following some notes and articles on the "Cannot load libwebp.dll"
i installed: 
Vanjaro_Platform_0.5.1_x64_Install
and additional:
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501
and later
Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.27.29016
both didn't resolve this. 

General Exception
AbsoluteURL /API/Image/upload/files DefaultDataProvider DotNetNuke.Da
AbsoluteURL:/API/Image/upload/files
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:b34efd5a-6e23-460d-ae0c-247270a61115
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:GotQuohgqmP+A90oxuy27a1c74Q=
Message:The type initializer for 'ImageProcessor.Plugins.WebP.Imaging.Formats.NativeMethods' threw an exception.
StackTrace:
at ImageProcessor.Plugins.WebP.Imaging.Formats.NativeMethods.WebPFree(IntPtr pointer) at ImageProcessor.Plugins.WebP.Imaging.Formats.WebPFormat.EncodeLossly(Bitmap bitmap, Int32 quality, Byte[]& webpData) at ImageProcessor.Plugins.WebP.Imaging.Formats.WebPFormat.Save(Stream stream, Image image, Int64 bitDepth) at ImageProcessor.ImageFactory.Save(Stream stream) at Vanjaro.Common.Factories.BrowseUploadFactory.CropImage(String FileName, String FileExtension, IFolderInfo FolderInfo, Stream FileStream) at Vanjaro.Common.Factories.BrowseUploadFactory.SaveFile(HttpFileCollection files, IFolderInfo folderInfo, Int32 i, String& Response, Int32 maxsize, String filetypes) at Vanjaro.Common.Factories.BrowseUploadFactory.SaveFiles(HttpContext context, HttpFileCollection files, PortalSettings portalSettings)
InnerMessage:Cannot load libwebp.dll
InnerStackTrace:
at ImageProcessor.Configuration.NativeBinaryFactory.<>c__DisplayClass7_0.<RegisterNativeBinary>b__0(String b) at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) at ImageProcessor.Plugins.WebP.Imaging.Formats.NativeMethods..cctor()
Source:ImageProcessor.Plugins.WebP
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: vmi29

i checked to see if the MSVCR120.DLL is on the system. it is in C:\windows\system32\
product name on properties: Microsoft Visual Studio 2013 
product version 12.00.21005.1
(server 2016)

**Comment by meetmandeep** [comment]
@paulfijma Can you tell me more about your hosting environment? This issue was surfaced in alpha release and since has been resolved. 

- Is this on your own dedicated server or shared server? 
- Hosting Provider? 

Feel free to send me a Private Message on Slack. I'm very curious to learn more.

**Comment by paulfijma** [comment]
@meetmandeep :
VM: "VPS S SSD"  from www.contabo.com technically a shared environment, the server is private, and running with SSD.  
OS: Windows Server 2016 Datacenter Edition (64 Bit) 
CPU
	Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
	Maximum speed:	2.20 GHz
	Sockets:	1
	Virtual processors:	4
	Virtual machine:	Yes
	L1 cache:	N/A
	Utilization	13%
	Speed	2.20 GHz
	Up time	8:11:15:55
	Processes	71
	Threads	1280
	Handles	42428
No strange software of control stuff installed. no updates pending.. (all up to date)
i'll try to make some time today and make a hyper-v server 2016. then i will install vanjaro and test it. 

**update:**
someone with a similar problem: https://github.com/JimBobSquarePants/ImageProcessor/issues/764
pointed out he had to install the x86 version of Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.30501
**Have installed it and the error is gone.** 
addendum:
there are now two MSVCR120.DLL files. One in windows\system32, and one in windows\SysWOW64
(to make it complete: 
there is also one MSVCR120.DLL in c:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18221\  )

**Comment by meetmandeep** [comment]
Let's compare your IIS Options. Here's what my local machine looks like:

![image](https://user-images.githubusercontent.com/29958123/94311682-84d0a200-ff30-11ea-997d-5da8647d5ae4.png)

**Comment by paulfijma** [comment]
Hi Mandeep,
my bad, your mail was hidden in The Spam Box...
The compare is a little confusing :-)

but... powershell to the rescue.  it's safe to run, but all the criminals say the same :-)
This is the script i use to create a list of features from a working server. I have a similar script that uses the same output to install the missing features...
as long as servers are the same version it will work. When upgrading to a newer version the names and available items might change. 

this method still beats image compare ;) 

###########################################
#
#the basic commands
#

$Allfeatures = get-windowsfeature 
$Allfeatures
$Allfeatures | where {$_.installstate -eq 'installed'}

###########################################
 

# SCRIPT TO MAKE A LIST -  copy paste in file, save as get-featureslist.ps1
#run with elevated rights (as admin)
###########################################
<#
Create List of installed Windows Features
Example output:
PS C:\install> Get-WindowsFeature

Display Name                                            Name                       Install State
------------                                            ----                       -------------
[ ] Active Directory Certificate Services               AD-Certificate                 Available
    [ ] Certification Authority                         ADCS-Cert-Authority            Available
    [ ] Certificate Enrollment Policy Web Service       ADCS-Enroll-Web-Pol            Available
    [ ] Certificate Enrollment Web Service              ADCS-Enroll-Web-Svc            Available

...
#>

Function New-WindowsFeaturesList{
[CmdletBinding()]
    Param (
        [string]$filename = '.\FeaturesList.txt'
    )

#get all features
$Allfeatures = get-windowsfeature 

#show all found features
$Allfeatures
# 'Found Total Features: {0}' -f $Allfeatures.count
$InstalledFeatures = ($Allfeatures | where {$_.installstate -eq 'installed'})
# 'Found number Install: {0}' -f $InstalledFeatures.count

$flist = @()
foreach ($feature in $InstalledFeatures){
    $flist+=($feature.name)
}
#create a list with all installed modules
#$c = ($InstalledFeatures | select name | ft -HideTableHeaders) | ? { -not [String]::IsNullOrWhiteSpace($_) -and $_ -notlike '#*'}
#$c.count
$flist | out-file $filename -Encoding ascii
}

#usage:
New-WindowsFeaturesList features_svr2016.txt
notepad features_svr2016.txt


 

 

###########################################

 

 

 

 


OUTPUT MY LIST:

FileAndStorage-Services
Storage-Services
Web-Server
Web-WebServer
Web-Common-Http
Web-Default-Doc
Web-Dir-Browsing
Web-Http-Errors
Web-Static-Content
Web-Health
Web-Http-Logging
Web-Performance
Web-Stat-Compression
Web-Security
Web-Filtering
Web-App-Dev
Web-Net-Ext45
Web-Asp-Net45
Web-ISAPI-Ext
Web-ISAPI-Filter
Web-Mgmt-Tools
Web-Mgmt-Console
NET-Framework-45-Features
NET-Framework-45-Core
NET-Framework-45-ASPNET
NET-WCF-Services45
NET-WCF-TCP-PortSharing45
FS-SMB1
Windows-Defender-Features
Windows-Defender
Windows-Defender-Gui
PowerShellRoot
PowerShell
PowerShell-ISE
WoW64-Support

 


 

 

Sent: Friday, September 25, 2020 at 10:11 PM
