### ISSUE TITLE
Add existing module to a page

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#371]
In DNN I use 'existing module to a page' on a regular basis. 2 use cases:

1. existing module where all instances get updated if 1 gets updated (linked) : Designed content that is put on several pages. Like banners or Call to action rows
2. existing module to quickly make slight changes (copy): if you have a form that is almost identical but just needs another email-to-address or thankyou-page

**Comment by meetmandeep** [comment]
The idea in Vanjaro is to not use the HTML module to build the site. You can easily use Global Blocks to update content across several pages. 

Add existing modules is extremely handy for developers or power users but creates confusion down the road for end users. I can see the value in creating a copy of a module but I'm not sure how this will fit in with existing Vanjaro UX Manager. 

We'll be happy to consider this in future but this will likely not be part of initial release.
