### ISSUE TITLE
Background Image Icon on Styling tab

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#389]
![image](https://user-images.githubusercontent.com/6786299/101510339-6bd86a00-393f-11eb-923b-a2bd8d89f549.png)
It would be more intuitive to add a image icon here, rather than the click on pen image and then a little + icon to add a background image.

**Comment by meetmandeep** [comment]
Both Background Color & Image can be used in a combination and therefore share the same tab/icon. Perhaps, we can change the paint brush icon to something else. 

Feel free to suggest an icon from Font Awesome: https://fontawesome.com/icons?d=gallery&m=free

**Comment by scottw12** [comment]
I agree with mandeep in that Background-color and background-image are mutually used in most cases. It's just that that darn little "+" is hard to see and doesn't really indicate a place to upload an image.  How about increasing the size of the plus a bit and add "Upload Image" text centered under the plus sign. Will help that to stick out a bit more. Personally I would appreciate text like "image" on that section we are talking about be darker all around.

**Comment by meetmandeep** [comment]
@scottw12 when you hover over the + icon a caption appears with words "Choose File". Would it help if the caption was always visible and said "Choose Background Image" ?

**Comment by scottw12** [comment]
Yes that reads good
