### ISSUE TITLE
Losing styles when dragging a block onto the page.

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#390]
I have had this happen several times and it has been a bugger to figure out what happened. It has happened when I have added bad CSS code to "Custom Styling". I have been able to go into the portal.css file and remove the offending code.

This is the page without being logged in.
![image](https://user-images.githubusercontent.com/6786299/101514138-90821100-3942-11eb-8a61-395dd8fe78ae.png)

This is the page when I log in:
![image](https://user-images.githubusercontent.com/6786299/101514546-00909700-3943-11eb-9381-81c9d01eb441.png)

This happened immediately after I drug a button block onto the page and clicked on the button.

**Comment by scottw12** [comment]
Update:  After finding out I could go to /site/signin I was able to restart the website and clear caches then all worked again.

**Comment by meetmandeep** [comment]
@scottw12 Are you able to duplicate the issue? If so, please provide step by step instructions.

**Comment by scottw12** [comment]
I am not sure exactly what triggers the issue.. I got back in went back 2 revisions and then added the button block again and all was well. It is the type of bug we hate. Very random. I do however notice many times that I can click on a block in the design area and it does not select. Sometimes I have to refresh the page to make it editable again.  Maybe related I don't know.

**Comment by meetmandeep** [comment]
Next time you run into the issue (of unable to select a block) then take a look at console for any errors.

**Comment by scottw12** [comment]
Will do.  Speaking of console I had turned off warnings on my FF browser because it was full of warnings. Chrome does not show them. I know things are in flux with all this cross site stuff. 
![image](https://user-images.githubusercontent.com/6786299/101523073-b82aa680-394d-11eb-8276-2a700da7444e.png)

**Comment by scottw12** [comment]
Just FYI I cleared all caches and restarted Vanjaro and on a clean reload I have no issues in the console (chrome). After Sign in I get:
![image](https://user-images.githubusercontent.com/6786299/101523710-90880e00-394e-11eb-99d2-ac2276bd196d.png)

**Comment by meetmandeep** [comment]
@scottw12 Look for errors in console when you run into the issue you described earlier.

**Comment by scottw12** [comment]
Page frozen, cannot select, and the selected column has not menu on it.
![image](https://user-images.githubusercontent.com/6786299/101526316-0e014d80-3952-11eb-9d8b-27deaa4a5078.png)
 Chrome Console:
![image](https://user-images.githubusercontent.com/6786299/101526395-2cffdf80-3952-11eb-9e69-cc05072330e3.png)

**Comment by scottw12** [comment]
After a period of time and several clicks all over the pages it breaks loose and start working again.

**Comment by meetmandeep** [comment]
Possibly related to #590 

I'm unable to duplicate the issue after resolving #590 in RC.
