### ISSUE TITLE
Max Height and Min-Width 

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#394]
Would be very useful to  have  min-width and a max-height sliders in the Layout & Dimensions section.  Images can have a tendency to get too high when working on responsive layouts. Also widths can get too narrow. I commonly use Min-width or columns.

**Comment by Tychodewaard** [comment]
While we are in this area...overflow as well? Especially the hidden part.

**Comment by meetmandeep** [comment]
Excellent suggestions by @scottw12  and @Tychodewaard . We're working on improving Styling Tab so it's perfect time to address this.
