### ISSUE TITLE
Spinners are very sporadic

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#395]
1. Text input with spinner boxes do not behave well.  Very seldom can I select a input box with spinner and use my up/down arrow keys to change values.

2. Input in areas is so small the spinner is next to impossible to use even with mouse selection.  
Part of my problem may be that I run 19200 - 3840  widths on my screen resolution, but I havent had the selectivity problems with the spinner arrow.

Second issue is minor and a nuisance but the first issue is a must IMHO. it is tough to use mouse for spinners when the do not auto up or down or you cannot use keyboard.

**Comment by meetmandeep** [comment]
We're working on improving the Styling Tab by removing spininers (Up/Down arrows) and making sure each text box has a slider

**Comment by scottw12** [comment]
Wasn't really wanting spinners removed. I think it is very beneficial to have a way to nudge values 1 by one. We all do it in the debugger. select the value of the width and move it one by one with arrow keys. To me me that is a desirable function.  Click in a numeric field and use the keyboard arrow keys to move up or down by 1....

**Comment by meetmandeep** [comment]
@scottw12 Basically, we need to make sure that the spinners respond to the keyboard?

**Comment by meetmandeep** [comment]
Update: 

- Keyboard arrow keys & Mouse wheel does not work w/Text Inputs if they're associated with a slider.

**Comment by scottw12** [comment]
I disagree with that, but OK.

**Comment by meetmandeep** [comment]
@scottw12 My research indicated that the issue only exists if the textbox is associated with a slider. Is that not the case?

**Comment by scottw12** [comment]
Not out of the box. Would require an event handler in java to watch for the keypress and change the value properly.

**Comment by scottw12** [comment]
I have noticed that the font size slider/textbox on the options tab work with keyboard just fine.
