### ISSUE TITLE
Unable to save page when using design block in global block

### ISSUE THREAD

**Issue by Gaganbird** [vanjarosoftware/Vanjaro.Platform#398]
Steps to duplicate:

- Add Section 
- Add Grid within it
- Add Breadcrumb within the column
- Menu > Save As Block
- Global Block > Update
- Add Global Block to the page and Unlock 
- Publish

![image](https://user-images.githubusercontent.com/52308516/101618397-f2707280-3a37-11eb-8b38-98d73600cc18.png)
![image](https://user-images.githubusercontent.com/52308516/101618466-05834280-3a38-11eb-8e50-0bdacf1a497d.png)

**Comment by hshimanshusharma** [comment]
@Gaganbird now the issue not duplicating, maybe it's fixed confirm and close the issue

**Comment by mksmanish79** [comment]
i am also not able to duplicate the issue
