### ISSUE TITLE
Image inside a Link Block loses styling when duplicated

### ISSUE THREAD

**Issue by joshgk00** [vanjarosoftware/Vanjaro.Platform#400]
I found a bug with the Link Block. When it's duplicated with an image inside and/or a Text block, the styling settings are lost when changing the image.
Setup:

- Add a Grid with at least 1 column. 
- Add a Link Block
- Add the following inside the Link Block
  - Image Block
  - Text Block
- Add bottom margin to the image
- Add a Box Shadow to the image
- Select the Column and click the Copy button to duplicate
- Double-click the newly duplicated image to change the image.
- When the File Manger opens, double-click a new image to use the image
- Click to another element on the page, you'll notice that the margin on the image and box shadow and other settings appear to be gone

If the items are not contained in a Link Block they seem to duplicate correctly and the styles are retained. 

Here's a screencast of what I'm seeing
https://www.screencast.com/t/ubll10WtX

**Comment by meetmandeep** [comment]
@joshgk00 Thanks for reporting this. I'm able to duplicate this.
