### ISSUE TITLE
Feature request: ability to add devices

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#403]
Love the switch devices. If it is not too much trouble...would it be possible to have the ability to add devices? So:

- width
- height
- Store as [nameDevice]

**Comment by meetmandeep** [comment]
It's not just a switch to see how the site looks in other devices; it's also integrated with responsive design and plays a key role with optimizing images for responsive web. 

So we cannot just arbitrary add new devices without breaking other functionality.
