### ISSUE TITLE
Installation Log not visible after clean install

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#404]
After installing a clean site the Install/InstallWizard.aspx?culture=en-US&acceptterms=true&executeinstall page indicates "No Installation Log"

![image](https://user-images.githubusercontent.com/6786299/101809532-4bdead00-3add-11eb-9b8c-cda5407d5037.png)

**Comment by meetmandeep** [comment]
I believe that is the intended functionality by DNN; the log only appears when there are errors or issues.
