### ISSUE TITLE
Uploading Images Breaks Image Preview on Image Gallery Blocks

### ISSUE THREAD

**Issue by joshgk00** [vanjarosoftware/Vanjaro.Platform#408]
I dragged an Image Gallery block on the page. If I double click on an image to change it and upload a new image, it breaks the image preview and when finally selecting the image you want, it disappears from the page. 

Here's a screencast:
https://www.screencast.com/t/a2KHr1deOq

Steps to reproduce:
- Drag image gallery onto page
- Double-click the image
- Choose a default image that comes with the default install
  - You'll notice that the image preview works
- Double Click the image to use it
  - The image updates on the page
- Double Click another image on the gallery
- Upload an image to the site
- Click once on the image to preview
  - The image disappears from the page
- Double click the newly uploaded image to add it to the gallery

The image doesn't appear in the gallery so it's unclear if the image is actually saved to the gallery

**Comment by meetmandeep** [comment]
Thanks for reporting this. I'm able to duplicate this.

**Comment by meetmandeep** [comment]
This issue has been resolved in RC.
