### ISSUE TITLE
No choice available for rem

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#416]
I have noticed that there is no choice for rem in the sizing of things... It would be nice to have that.

**Comment by meetmandeep** [comment]
We're simplifying the choices; there will be only px (default) and vw (responsive / viewport width) available.

**Comment by scottw12** [comment]
The greatest power that rem units offer is not just that they give consistent sizing regardless of element inheritance. Rather, it’s that they give us a way to have user font size settings influence every single aspect of a site’s layout by using rem units where we used to use px units. vw will frustrate many people before they figure out that it is but a percentage. REM units gives us flexibility in our designs, and the ability to scale elements up and down, instead of being stuck with fixed sizes. We can use this flexibility to make our designs easier to adjust during development, more responsive, and to allow browser users to control the overall scale of sites for maximum readability.

**Comment by meetmandeep** [comment]
@scottw12 rem is available from Styling Tab > Font Size. It will not be available under "Options" of a block for simplicity. Those two options will be limited to px and vw but you have full range of options including px, %, em, rem, and vw (coming in RC) under Styling Tab.

**Comment by scottw12** [comment]
I am closing this issue since the main focus of using rem units is for responsive text uses and that it is 
already included.
