### ISSUE TITLE
rename Upload a file

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#418]
If you want to delete a file in Vanjaro, the only way (I think) is to go to 'upload a file'
![image](https://user-images.githubusercontent.com/9091997/102342921-39131f00-3f9a-11eb-9c0b-951d62710162.png)

Wouldn't it make more sense to call it 'file manager'? Because you can also delete, rename

**Comment by meetmandeep** [comment]
@Tychodewaard That's a shortcut menu to add new items such as a new page, user, role, or file. 

You're correct that it takes user to "Assets". There is already a dedicated link to "Asset Manager" from Site > Assets.
