### ISSUE TITLE
Font Awesome CSS not loading for anonymous users

### ISSUE THREAD

**Issue by joshgk00** [vanjarosoftware/Vanjaro.Platform#419]
I ran into a bug. I added some custom code to show an icon from the Font Awesome stylesheet. I realize there's an icon block for this but I'm using this html for a structured content template. 

When I add the HTML to show an icon from Font Awesome it shows up as intended when logged in and when in preview mode. It appears that the Font Awesome stylesheet isn't being loaded when not logged in.

Steps to reproduce:
- Create a page
- Add a Custom HTML block to the page
- Add the following HTML to the block `<i class="fas fa-play" style="margin-right:20px;"></i> This is a test`
- Click Update
- Publish the page. The icon shows when logged in
- Open new browser, Incognito mode and navigate to the page
- You'll see that the icon doesn't show up

Here's a screencast of what I'm seeing
https://www.screencast.com/t/3bCK84AkJ

**Comment by meetmandeep** [comment]
@joshgk00 This is by design. FontAwesome CSS Library is only used for admin UI and is not loaded in frontend for performance. You'll need to add your own dependencies if you need the FontAwesome library. 

We recommend using the SVG icons instead which our Icon Block uses.

**Comment by joshgk00** [comment]
Are there any dependencies needed on the front end for SVG icons?  Do you have a quick example of how to add one?

**Comment by meetmandeep** [comment]
No. SVG are supported natively by browsers. See: https://caniuse.com/svg

Drag an icon block on the page and inspect/view source for an example. Thanks
