### ISSUE TITLE
Images disappear

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#420]
I have a grid with logo's (customers) and sometimes images, created with the Vanjaro 'image'  block disappear. At first I thought it was just me but  there seems  to be funky stuff going on.
1. Where an image was missing, I saw in the navigator that in the column, there were multiple image boxes. 'Solution' was deleting those and start fresh
2. But I also have a column with just 1 image box that is not being displayed. So, there is no 'clash of image boxes needed for not displaying the image.
![image](https://user-images.githubusercontent.com/9091997/102467075-2529f480-4050-11eb-885b-855cbbe46edc.png)

3. If I inspect the element of the non visible image, I can see, that the  source has the image.
![image](https://user-images.githubusercontent.com/9091997/102467250-5b677400-4050-11eb-9221-da5c79c0a0c8.png)

4. If I look in the console, I see a lot of red....
![image](https://user-images.githubusercontent.com/9091997/102467670-db8dd980-4050-11eb-9983-729cdec5ed54.png)

**Comment by Tychodewaard** [comment]
If there is any idea what the cause is or the scenario, I might be able to prevent this in the current setups. Any input would be appreciated.

**Comment by meetmandeep** [comment]
@Tychodewaard We're still working on this issue; one of the last ones before we release RC. 

We're able to duplicate this issue if the file name (image path) has spaces in it. I can see from your screenshot that the image name has spaces in it as well. For immediate workaround, make sure your images don't have spaces in them and see if that works. The team is working on a permanent solution.

**Comment by Tychodewaard** [comment]
It also happens for images called voor.png and na.png. So, without spaces.

But I’ll remove the spaces where applicable. Thanks for the feedback!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Mandeep Singh <notifications@github.com>
Verzonden: Wednesday, January 13, 2021 10:07:48 PM
Aan: vanjarosoftware/Vanjaro.Platform <Vanjaro.Platform@noreply.github.com>
CC: Tycho de Waard <info@tjeps.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [vanjarosoftware/Vanjaro.Platform] Images disappear (#420)


@Tychodewaard<https://github.com/Tychodewaard> We're still working on this issue; one of the last ones before we release RC.

We're able to duplicate this issue if the file name (image path) has spaces in it. I can see from your screenshot that the image name has spaces in it as well. For immediate workaround, make sure your images don't have spaces in them and see if that works. The team is working on a permanent solution.

**Comment by meetmandeep** [comment]
Can you duplicate the issue? If not, do you have a page where the issue currently exits? It would help to get a copy of the page so we can replicate.

**Comment by Tychodewaard** [comment]
I have an example where images disappear where the name of the images does not contain a space
On http://tjeps04.tip15.40fingers.eu/ 
![image](https://user-images.githubusercontent.com/9091997/105376209-ce44ab80-5c09-11eb-98d3-dab2a58ee798.png)
There are only 2 customer logos visible today where yesterday there were 4.

**Comment by meetmandeep** [comment]
@Tychodewaard Thanks for the link. We were able to duplicate this issue. It will be resolved in RC. 

FYI: Images are being set to 0 x 0px during the "Optimizing Images" phase when you publish a page. For now, be sure to verify all images after you click on publish button.
