### ISSUE TITLE
Vanjaro hangs up when going between full screen and open manager bar.

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#423]
The hang up is sporadic. I will be working along in edit mode, press publish, close bar, refresh to clear page cache and then open manager. Or even just click on a another  control and back....

The page goes grey and I get the Vanjaro loading spinner. and all is locked up. I can hit refresh on the browser and things start working again.  

Here is a sample of the console log from chrome and I have included a complete log file.
![image](https://user-images.githubusercontent.com/6786299/102541127-a647b280-4075-11eb-92bf-a8b781f484d9.png)
[dev.jcesba.org-1608237351220.log](https://github.com/vanjarosoftware/Vanjaro.Platform/files/5712020/dev.jcesba.org-1608237351220.log)

**Comment by meetmandeep** [comment]
This issue has been resolved in RC. Possibly related to #590
