### ISSUE TITLE
Manage buttons shown

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#425]
I have a Live knowledge base on http://tjeps02.40ftip11.40fingers.eu/roomburgerparkleiden/Q-A in a Vanjaro setuip. 
The 'manage' button of the extension is visible vor users that are not logged in. And I could also do without the 'knowledgebase button :-) 

Is this a Vanjaro thing or an extension thing?

**Comment by meetmandeep** [comment]
Not a Vanjaro thing 😄 

Knowledgebase button is a feature of the module. It may be possible to remove it. The "manage" button is a bug with the module. I would open a support ticket for both of these issues on www.mandeeps.com
