### ISSUE TITLE
Unable to Change the Font Color of Menu Block

### ISSUE THREAD

**Issue by ashishpachauriap** [vanjarosoftware/Vanjaro.Platform#5]
I have a section that contains a menu block and I added a dark background image to the section but the color of the menu still shows as a dark grey which makes it hard to read. Is there a way to change the font color of the menu? Is this part of the default theme? Below is a screenshot that shows the dark background and the menu that is hard to read. I'm hoping that there's a way before the final release to change the font color for the menu when it appears on a dark background. 

https://www.screencast.com/t/qbAgEp9yOJ

**Comment by meetmandeep** [comment]
This is now possible using the Theme Editor.
