### ISSUE TITLE
Too many redirections

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#53]
If I try to create a page, I get a blank screen with 'error, too many redirections.'.
This is on a DNN 7.0, beta release Vanjaro module.

**Comment by meetmandeep** [comment]
Was this on a new DNN Install of 9.7.0 or existing DNN site?

**Comment by Tychodewaard** [comment]
New install

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Mandeep Singh <notifications@github.com>
Verzonden: Monday, September 7, 2020 11:06:55 PM
Aan: vanjarosoftware/Vanjaro.Platform <Vanjaro.Platform@noreply.github.com>
CC: Tycho de Waard <info@tjeps.com>; Author <author@noreply.github.com>
Onderwerp: Re: [vanjarosoftware/Vanjaro.Platform] Too many redirections (#53)


Was this on a new DNN Install of 9.7.0 or existing DNN site?

**Comment by Tychodewaard** [comment]
Probably related: 
- install of Vanjaro_For_DNN_0.5.0_x64_Install on DNN 9.7.0 on my server at managed.com 
- create page (not a Vanjaro page, just a DNN page) creates 500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed.
- In the admin log it says:
AbsoluteURL:/API/personaBar/UserSettings/UpdateUserSettings

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:8597a883-53bc-43da-bf62-ca7d21156164

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:WvF7eNveo9Q9W3l6DalV8hG4dpM=

Message:During loading of Sass compiler error has occurred. See the original error message: “An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)”.

StackTrace:

   at LibSassHost.SassCompiler.Initialize()
   at LibSassHost.SassCompiler.InnerCompile(String content, Boolean indentedSyntax, String inputPath, String outputPath, String sourceMapPath, CompilationOptions options)
   at LibSassHost.SassCompiler.Compile(String content, String inputPath, String outputPath, String sourceMapPath, CompilationOptions options)
   at Vanjaro.Core.Managers.ThemeManager.ProcessScss(Int32 PortalID)
   at Vanjaro.Core.Managers.SettingManager.DoIUpgradeable(PortalInfo pinfo)
InnerMessage:An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

InnerStackTrace:

   at LibSassHost.Internal.Native.Sass_Api.libsass_version()
   at LibSassHost.SassCompiler.Initialize()
Source:LibSassHost

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: N11627VDC1A000A

As it refers to sass, it has to do with Vanjaro as a vanilla DNN does not use sass

**Comment by meetmandeep** [comment]
> An attempt was made to load a program with an incorrect format. 
This indicates that 32 bit package was installed on 64 bit IIS App Pool or vice a versa.

**Comment by meetmandeep** [comment]
This issue may exist with multiple portal aliases and canonical redirection. 

**Steps to reproduce:**
1. Install new instance of DNN 9.7.0
2. Add another portal alias w/canonical redirection
3. Install Vanjaro Extension
4. Click on "Migrate This Page" results in too many redirects...

**Comment by Tychodewaard** [comment]
The issue was actually multiple aliasses in IIS. When I removed the second one, all was well. The DNN instance itself still had multiple site aliasses

**Comment by Tychodewaard** [comment]
Or maybe both...I'm not sure anymore...time for a good night sleep

**Comment by meetmandeep** [comment]
@Tychodewaard Is this still an issue for you or can I close this? I was unable to reproduce.

**Comment by Tychodewaard** [comment]
Strangely enough, neither can I.
Added alias in DNN: works
Added alias in IIS: works
Migrate page to Vanjaro: gives a blank screen where you'd expect a page with global blocks but that's not an error and probably just learning how things work.
