### ISSUE TITLE
Related to closed issue #18

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#537]
Live Slider image issue I still have using Vanjaro 0.5.3 (BETA) and Live-Slider v8.0.6 I do not always get the critical error but I cannot upload or select an an image. No errors apparent.

**Comment by scottw12** [comment]
I also see this at the bottom of the page when I go in a second time. There are no errors in browser dev tools, I.E. logs, Vanjaro logs or system logs that I can find.

![image](https://user-images.githubusercontent.com/6786299/104621765-14bc6800-5656-11eb-8925-5d314b5e64e4.png)

**Comment by scottw12** [comment]
Please let me know if this is the place for this reporting for forward me to where it needs to go. Thanks

**Comment by scottw12** [comment]
On the image above if I click on that "No Image" button I get in that iframe a 403 - forbidden error when it tries to load http://dev.jcesba.org/slider/ctl/imagepicker/mid/418/controlid/dnn_ctr418_Manage_ctl52_ImgBackgroundImage?popUp=true

**Comment by meetmandeep** [comment]
> Please let me know if this is the place for this reporting for forward me to where it needs to go

@scottw12 This is the correct place to log any issues with Vanjaro; whether with Mandeeps.com or any other 3rd party extensions. Thanks

**Comment by meetmandeep** [comment]
Thanks for reporting this issue. This has been resolved in RC. You will also need to download the latest version of Live Slider at time of RC release.
