### ISSUE TITLE
Problems with Live-Forms Structure designer.

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#546]
When creating or editing a Live Form the Structure  Designer is mal-formed and at times impossible to use.
When dragging a field on the form the highlighted drop zone is often incorrect.
Occasionally when scrolling to the bottom of the designer it jumps up from the bottom and wont stay on the bottom.
When in the middle of a form the the menu bar jumps into the middle of the screen making editing very difficult.
Menu is not sticky to top.
Designer window cannot be opened full screen.
![image](https://user-images.githubusercontent.com/6786299/104951859-fa052e80-5988-11eb-8512-37364ebb0e7b.png)

**Comment by meetmandeep** [comment]
Thanks for reporting this. Vanjaro is getting its own version of Live Forms that is integrated with Vanjaro and provides a native UX. It will retain all features of Live Forms and will address all UX issues. 

Watch out for new Form Builder for Vanjaro along with Vanjaro's official release.
