### ISSUE TITLE
Cannot use Live-Slider

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#556]
It installed fine and the manage screen comes up normal. When I click on Image placeholder to select an image I located the image I want and click select. The select screen closes but no image was selected. When I try to upload a new file I get the error: "An error occurred when attempting to save the file logo_footer.png. Contact your hosting provider to ensure the appropriate security settings have been enabled on the server."  I have checked the security on the folder where the file is placed and there is no reason on that folder to prevent an upload. 

I have seen the following errors from the console of the browser:
slider-test:239 Uncaught TypeError: $(...).dnnModuleActions is not a function
    at setUpActions (slider-test:239)
    at slider-test:349
    at dispatch (js:1)
    at v.handle (js:1)

dnn_ctr438_Manage_ctl52_ImgBackgroundImage?popUp=true:67 Uncaught TypeError: $(...).dnnModuleActions is not a function
    at setUpActions (dnn_ctr438_Manage_ctl52_ImgBackgroundImage?popUp=true:67)
    at dnn_ctr438_Manage_ctl52_ImgBackgroundImage?popUp=true:177
    at dispatch (js:1)
    at v.handle (js:1)

**Comment by meetmandeep** [comment]
Thanks for reporting this issue. This has been resolved in RC. You will also need to download the latest version of Live Slider at time of RC release.
