### ISSUE TITLE
Unable to add images

### ISSUE THREAD

**Issue by ashishpachauriap** [vanjarosoftware/Vanjaro.Platform#608]
- Drop image block on the page
- Double click on image block to add image
- Apply a image by double clicking on any image

See https://drive.google.com/file/d/1RtEnRrRw8CsEUmDmZok2HtL9_cajvrc-/view

**Comment by Gaganbird** [comment]
![image](https://user-images.githubusercontent.com/52308516/105998251-722ecb00-60d2-11eb-9aeb-5eb73689b335.png)
