### ISSUE TITLE
Styling logged in different from not logged in

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#611]
I have a custom block with a testimonial caroussel. Just HTML and CSS.
On https://www.heartfulmoments.nl/nl-nl/Mindful-thuiswerken you don't see left or right chevron but when logged in, I can see them (as expected and wanted).

**Logged in:**
![image](https://user-images.githubusercontent.com/9091997/105894182-49480080-6014-11eb-8ce9-85d4de1fd055.png)

**Not logged in:**
![image](https://user-images.githubusercontent.com/9091997/105894244-582eb300-6014-11eb-85aa-73adaa0d886c.png)

**Comment by meetmandeep** [comment]
I can confirm that the Carousel block is working fine. 

I don't see the chevron icon (controls) in the markup you used in Custom Block. We can further investigate this if you can provide the exact markup that's in the custom block. Please also indicate if the block is Local or Global?

**Comment by Tychodewaard** [comment]
It is a local custom block. the  previous and next butttons are at the bottom of the HTML:

<section class="pb-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-8 mx-auto">
                <div class="p-5 bg-white shadow rounded">
                    
                    <div class="carousel slide" id="carouselExampleIndicators" data-ride="carousel">
                        
                        <ol class="carousel-indicators mb-0">
                            <li class="active" data-target="#carouselExampleIndicators" data-slide-to="0"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        </ol>


                        
                        <div class="carousel-inner px-5 pb-4">
                            
                            <div class="carousel-item active">
                                <div class="media"><img class="rounded-circle img-thumbnail" src="https://res.cloudinary.com/mhmd/image/upload/v1579676165/avatar-1_ffutqr.jpg" alt="" width="75">
                                    <div class="media-body ml-3">
                                        <blockquote class="blockquote border-0 p-0">
                                            <p class="font-italic lead"> <i class="fa fa-quote-left mr-3 text-info"></i>Irene heeft ons op een plezierige manier aan het denken en reflecteren gezet. Haar werkwijze en vooral coachende stijl maakt echt een verschil. Zeker aangezien we nu  zelf verder moeten.</p>
                                            <footer class="blockquote-footer">HR Manager
                                                <cite title="Source Title">multinational</cite>
                                            </footer>
                                        </blockquote>
                                    </div>
                                </div>
                            </div>

                            
                            <div class="carousel-item">
                                <div class="media"><img class="rounded-circle img-thumbnail" src="https://res.cloudinary.com/mhmd/image/upload/v1579676165/avatar-3_hdxocq.jpg" alt="" width="75">
                                    <div class="media-body ml-3">
                                        <blockquote class="blockquote border-0 p-0">
                                            <p class="font-italic lead"> <i class="fa fa-quote-left mr-3 text-info"></i>Goede opbouw van de workshop, prettige combinatie van theorie,  oefeningen en aandacht voor de ervaringen en vragen van de deelnemers. Irene creëert een hele open, vertrouwde online omgeving.</p>
                                            <footer class="blockquote-footer">Manager
                                                <cite title="Source Title">verzekeraar</cite>
                                            </footer>
                                        </blockquote>
                                    </div>
                                </div>
                            </div>

                            
                            <div class="carousel-item">
                                <div class="media"><img class="rounded-circle img-thumbnail" src="https://res.cloudinary.com/mhmd/image/upload/v1579676165/avatar-2_gibm2s.jpg" alt="" width="75">
                                    <div class="media-body ml-3">
                                        <blockquote class="blockquote border-0 p-0">
                                            <p class="font-italic lead"> <i class="fa fa-quote-left mr-3 text-info"></i>Irene heeft geweldig werk geleverd door deze training te leiden met inzicht, kennis en vriendelijkheid. Ze is een enthousiaste, competente trainer. Ik heb echt genoten van de training mindful op het werk. </p>
                                            <footer class="blockquote-footer">Laborant
                                                <cite title="Source Title"></cite>
                                            </footer>
                                        </blockquote>
                                    </div>
                                </div>
                            </div>
                        </div>


                        
                        <a class="carousel-control-prev width-auto" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <i class="fa fa-angle-left text-dark text-lg"></i>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next width-auto" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <i class="fa fa-angle-right text-dark text-lg"></i>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

**Comment by meetmandeep** [comment]
You're using "fa" for icon which is FontAwesome library that is only used for administration within Vanjaro's UX Mananger. FontAwesome library is not loaded for non-admins for performance. Your custom code must ensure that all required dependencies are available. 

Our recommendation is to use SVG icons (like Vanjaro does for Frontend) rather than using the FontAwesome CSS library for performance.
