### ISSUE TITLE
CSS of custom block persists after deletion

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#764]
If I have a custom block with my own css and later remove the custom block, the css somehow remains active.
It doesn't matter of you clear server cache, browser cache, update crm...

1. It would be great if this was not happening :-)
2. Any ideas where how this is stored? And how it can be deleted?

**Comment by Tychodewaard** [comment]
Some input:
In the source from the page there is a lot of styling and some of it is related to old custom blocks that have been deleted. In the code below all with .brands (nav, items etc) and the owl carousel are not on the page anymore. 

In the database I can see it residing in the column _styling_ from Vanjaro pages (VJ_Core_pages). AlternativelyTo edit this by SQL statements is quite a task and messy. 
Ideally these parts of the css will be removed after a block is removed. Alternatively, if there were an interface that shows (and allows to edit) this part (inline styling from the page) that would also be a solution. 

meta id="Vanjaro_Viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1 user-scalable=0" /><style type="text/css">.edn-article-list-row > div{display:flex;}#iuwcat{overflow-x:visible;overflow-y:visible;background-position-x:50%;background-position-y:50%;background-attachment:scroll;background-repeat-x:no-repeat;background-repeat-y:no-repeat;background-size:auto;background-image:none;background-color:rgb(227, 227, 227) !important;}#i6eaij{padding-top:0px;padding-bottom:0px;min-height:10px;overflow-x:visible;overflow-y:visible;background-position-x:50%;background-position-y:50%;background-attachment:scroll;background-repeat-x:no-repeat;background-repeat-y:no-repeat;background-size:auto;background-image:none;background-color:transparent;filter:hue-rotate(0deg) invert(0%);height:50vh;}#i2vgcx{padding-left:0px;padding-right:0px;background-color:rgb(245, 158, 56);min-height:10px;}#iaklyi{padding-left:0px;padding-right:0px;background-color:rgb(21, 106, 162);}#i1q8wo{padding-top:0px;padding-bottom:0px;min-height:50vh;}#igxcox{min-height:10px;}#inzvoq{padding-left:0px;padding-right:0px;background-color:rgb(237, 60, 86);}#ics9v7{padding-left:0px;padding-right:0px;background-color:rgb(0, 139, 44);}#ifl7kg{overflow-x:visible;overflow-y:visible;background-image:-webkit-linear-gradient(90deg, rgb(0, 126, 59) 1%, rgb(0, 154, 62) 99%);background-color:transparent;min-height:10px;padding-top:100px;padding-bottom:100px;}#i3mwxe{font-size:1.3em;font-weight:700;}#izru07{font-size:3em;font-weight:700;}#igl3sk{border-top-left-radius:0px;border-top-right-radius:0px;border-bottom-right-radius:0px;border-bottom-left-radius:0px;color:rgb(255, 255, 255);font-size:1.3em;background-color:rgb(245, 158, 56) !important;border-top-color:rgb(245, 158, 56) !important;border-right-color:rgb(245, 158, 56) !important;border-bottom-color:rgb(245, 158, 56) !important;border-left-color:rgb(245, 158, 56) !important;}#iagygb{text-align:right;}#ijdbtg{font-weight:700;font-size:4.3em;}#iz6j9c{overflow-x:visible;overflow-y:visible;background-image:-webkit-linear-gradient(-135deg, rgb(0, 126, 59) 1%, rgb(0, 154, 62) 99%);background-color:transparent;min-height:10px;height:35vh;padding-top:43px;padding-right:30px;padding-bottom:43px;padding-left:30px;}#if63np{padding-left:0px;}#ipx6va{font-weight:700;font-size:1.3em;}#i59gsu{font-size:3.0em;font-weight:700;}#i6eaij:hover{transition-duration:2s;transition-timing-function:ease;transition-delay:0s;transition-property:background-color;}#ixvook{background-attachment:scroll;background-size:cover;background-image:url("/Portals/0/markten/food.png?ver=RwyKwLx9R8YyxeNSAyBBxw%3d%3d");background-color:transparent;min-height:50vh;padding-top:0px;padding-bottom:0px;overflow-x:visible;overflow-y:visible;background-position-x:50%;background-position-y:50%;background-repeat-x:no-repeat;background-repeat-y:no-repeat;}#isekyv{font-size:4.3em;color:rgb(255, 255, 255);font-weight:700;padding-top:32vh;padding-left:5vh;}#ixvook:hover{filter:opacity(40%);}#in2d88{background-attachment:scroll;background-size:cover;background-image:url("/Portals/0/markten/industry.png?ver=RwyKwLx9R8YyxeNSAyBBxw%3d%3d");background-color:transparent;height:50vh;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;overflow-x:visible;overflow-y:visible;background-position-x:50%;background-position-y:50%;background-repeat-x:no-repeat;background-repeat-y:no-repeat;}#in2d88:hover{filter:opacity(40%);}#i83ove{background-attachment:scroll;background-size:cover;background-image:url("/Portals/0/markten/bagclosures.png?ver=RwyKwLx9R8YyxeNSAyBBxw%3d%3d");background-color:transparent;height:50vh;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;overflow-x:visible;overflow-y:visible;background-position-x:50%;background-position-y:50%;background-repeat-x:no-repeat;background-repeat-y:no-repeat;}#i83ove:hover{filter:opacity(40%);padding-top:0px;padding-bottom:0px;}#i1q8wo:hover{padding-top:0px;padding-bottom:0px;}#i9mjus{font-size:4.3em;color:rgb(255, 255, 255);font-weight:700;padding-top:40vh;padding-left:5vh;}#iopx9f{font-size:4.3em;color:rgb(255, 255, 255);font-weight:700;padding-top:40vh;padding-left:5vh;}#igzf5r{background-attachment:scroll;background-size:cover;background-image:url("/Portals/0/markten/medical.png?ver=RwyKwLx9R8YyxeNSAyBBxw%3d%3d");background-color:transparent;height:50vh;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;overflow-x:visible;overflow-y:visible;background-position-x:50%;background-position-y:50%;background-repeat-x:no-repeat;background-repeat-y:no-repeat;}#igzf5r:hover{filter:opacity(40%);}#i9dgjg{padding-left:0px;padding-right:0px;background-color:rgb(67, 207, 246);}#i0tbl7{overflow-x:visible;overflow-y:visible;background-position-x:50%;background-position-y:50%;background-attachment:scroll;background-repeat-x:no-repeat;background-repeat-y:no-repeat;background-size:cover;background-image:url("/Portals/0/843649350.png?ver=4FWM8ObWIKkrmYW0zdX3OA%3d%3d");background-color:transparent;height:50vh;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;}#izjetw{font-weight:700;font-size:4.3em;padding-top:40vh;padding-left:5vh;}#i33pqq{font-weight:700;font-size:4.3em;padding-top:40vh;padding-left:5vh;}#i0tbl7:hover{filter:opacity(40%);}#iuwf9g{text-align:center;}#ip907b{color:rgb(255, 255, 255);border-top-style:solid;border-right-style:solid;border-bottom-style:solid;border-left-style:solid;border-top-left-radius:0px;border-top-right-radius:0px;border-bottom-right-radius:0px;border-bottom-left-radius:0px;font-size:1.3em;background-color:rgb(245, 158, 56) !important;border-top-color:rgb(245, 158, 56) !important;border-right-color:rgb(245, 158, 56) !important;border-bottom-color:rgb(245, 158, 56) !important;border-left-color:rgb(245, 158, 56) !important;}.edn-article-list-row > div{display:flex;}#iy6q9g{overflow-x:visible;overflow-y:visible;background-position-x:50%;background-position-y:50%;background-attachment:scroll;background-repeat-x:no-repeat;background-repeat-y:no-repeat;background-size:cover;background-image:url("/Portals/0/Temp/thumbnail_image004.jpg?ver=f91ml8qIEwZPYtIk0DPsxA%3d%3d");background-color:transparent;height:245px;}#i8rnl4{color:rgb(255, 255, 255);border-top-left-radius:0px;border-top-right-radius:0px;border-bottom-right-radius:0px;border-bottom-left-radius:0px;font-size:1.3em;background-color:rgb(245, 158, 56) !important;border-top-color:rgb(245, 158, 56) !important;border-right-color:rgb(245, 158, 56) !important;border-bottom-color:rgb(245, 158, 56) !important;border-left-color:rgb(245, 158, 56) !important;}#ijkgob{border-top-left-radius:0px;border-top-right-radius:0px;border-bottom-right-radius:0px;border-bottom-left-radius:0px;font-size:1.3em;}body{background-image:initial;background-position-x:initial;background-position-y:initial;background-size:initial;background-repeat-x:initial;background-repeat-y:initial;background-attachment:initial;background-origin:initial;background-clip:initial;background-color:rgb(238, 238, 238);}.brands_item img{max-width:100%;}.brands_nav i{color:rgb(229, 229, 229);transition-duration:200ms;transition-timing-function:ease;transition-delay:0s;transition-property:all;}.brands_nav:hover i{color:rgb(103, 103, 103);}.owl-carousel .owl-item img{display:block;width:100px;height:auto;}.edn-article-list-row > div{display:flex;}.edn-article-list-row > div{display:flex;}#i07b5n{overflow-x:visible;overflow-y:visible;background-position-x:50%;background-position-y:0%;background-attachment:scroll;background-repeat-x:no-repeat;background-repeat-y:no-repeat;background-size:cover;background-image:url("/Portals/0/AREY20201209-0048-onbewerkt.jpg?ver=LeeESJkQ0Jm3cr92mbqBVg%3d%3d");background-color:transparent;min-height:739px;padding-top:0px;padding-bottom:0px;height:70vh;}#i0f1ay{top:auto;right:auto;left:auto;bottom:auto;padding-top:0px;padding-bottom:0px;overflow-x:visible;overflow-y:visible;background-position-x:50%;background-position-y:50%;background-attachment:scroll;background-repeat-x:no-repeat;background-repeat-y:no-repeat;background-size:auto;background-image:none;background-color:rgba(255, 255, 255, 0.8);}#ikhbol{top:auto;right:auto;left:auto;bottom:auto;}#i0147l{display:inline-block;margin-right:0px;top:auto;right:auto;left:auto;bottom:auto;}#itz8pq{top:auto;right:auto;left:auto;bottom:auto;position:static;}#i23l6y{top:auto;right:auto;left:auto;bottom:auto;padding-left:0px;padding-right:0px;}#ibf9qx{display:inline-block;}#idjz8j{top:auto;right:auto;left:auto;bottom:auto;text-align:right;padding-left:0px;padding-right:0px;position:static;}#iqgfxd{display:inline-block;}#iwtzvz{display:inline-block;}#iwc88i{font-size:4.6em;font-weight:700;}#ic2ytx{overflow-x:visible;overflow-y:visible;background-image:none;background-position-x:50%;background-position-y:50%;background-attachment:scroll;background-repeat-x:no-repeat;background-repeat-y:no-repeat;background-size:auto;padding-top:15vh;min-height:138px;background-color:rgba(36, 36, 36, 0.53) !important;height:661px;}.edn-article-list-row > div{display:flex;}.edn-article-list-row > div{display:flex;}.edn-article-list-row > div{display:flex;}.brands_item a{display:inline-block;position:relative;width:150px;height:150px;}.brands_item a img:first-of-type{transition-duration:0.5s;transition-timing-function:ease;transition-delay:0s;transition-property:all;transform-origin:center center;}.brands_item a img:nth-of-type(2){transition-duration:0.5s;transition-timing-function:ease;transition-delay:0s;transition-property:all;position:absolute;transform:scale(0);top:0px;left:0px;transform-origin:center center;}.brands_item a:hover img:first-of-type{transform:scale(0);}.brands_item a:hover img:nth-of-type(2){transform:scale(1);}.edn-article-list-row > div{display:flex;}.edn-article-list-row > div{display:flex;}.brands_item a.link{display:inline-block;position:relative;width:150px;height:150px;}.brands_item a.link .image-box:first-of-type{transition-duration:0.5s;transition-timing-function:ease;transition-delay:0s;transition-property:all;transform-origin:center center;}.brands_item a.link .image-box:nth-of-type(2){transition-duration:0.5s;transition-timing-function:ease;transition-delay:0s;transition-property:all;position:absolute;transform:scale(0);top:0px;left:0px;transform-origin:center center;}.brands_item a.link:hover .image-box:first-of-type{transform:scale(0);}.brands_item a.link:hover .image-box:nth-of-type(2){transform:scale(1);}.edn-article-list-row > div{display:flex;}.edn-article-list-row > div{display:flex;}.brands_item .image-box picture.picture-box{width:150px !important;height:150px !important;}.brands_item a.link:hover > .image-box:nth-of-type(1){transform:scale(0);}.brands_item a.link:hover > .image-box:nth-of-type(2){transform:scale(1) !important;}img.carousel-arrow{width:20px !important;}#i8bmqj{overflow:visible;background-position:center center;background-attachment:scroll;background-repeat:no-repeat;background-size:auto;background-image:-webkit-linear-gradient(90deg, rgb(1, 1, 1) 1%, rgb(112, 111, 111) 99%);background-color:transparent;padding-top:8px;padding-bottom:8px;}#iebcui{width:200px;}#i1sab6{text-align:right;}#isd3nl{text-align:center;width:40px;height:40px;background-color:#fbfbfb;border-width:1px;border-color:#ffffff;border-radius:25px;}#iv2cpt{padding-left:0px;padding-right:0px;background-image:none;width:40px;height:40px;border-radius:25px;background-color:transparent;}#i8vwtv{width:16px;height:26px;}#i8esvp{text-align:center;width:40px;height:40px;background-color:#fbfbfb;border-width:1px;border-color:#ffffff;border-radius:25px;}#i015ev{padding-left:0px;padding-right:0px;background-image:none;width:40px;height:40px;border-radius:25px;background-color:transparent;}#iayula{width:16px;height:26px;}#iluamz{text-align:center;width:40px;height:40px;background-color:#fbfbfb;border-width:1px;border-color:#ffffff;border-radius:25px;}#ivx0ug{padding-left:0px;padding-right:0px;background-image:none;width:40px;height:40px;border-radius:25px;background-color:transparent;}#i3khb1{width:16px;height:26px;}#idqvfv{display:inline-block;}#i9d5f5{background-color:#c6c6c6;}#izdc6r{background-color:transparent;font-size:12px;}@media (min-width: 576px) and (max-width: 767.98px){.slide-box img{flex-grow:0;flex-shrink:0;flex-basis:50%;max-width:50%;}}@media (max-width: 767.98px) and (min-width: 576px){.slide-box img{flex-grow:0;flex-shrink:0;flex-basis:50%;max-width:50%;}}@media (min-width: 768px) and (max-width: 991.98px){.slide-box img{flex-grow:0;flex-shrink:0;flex-basis:33.3333%;max-width:33.3333%;}}@media (max-width: 991.98px) and (min-width: 768px){.slide-box img{flex-grow:0;flex-shrink:0;flex-basis:33.3333%;max-width:33.3333%;}}@media (min-width: 992px){.slide-box img{flex-grow:0;flex-shrink:0;flex-basis:25%;max-width:25%;}}@media screen and (min-width: 1024px){.edn-article-list-row > div{padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px;}.edn-article-list-row > div{padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px;}.edn-article-list-row > div{padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px;}.edn-article-list-row > div{padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px;}.edn-article-list-row > div{padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px;}.edn-article-list-row > div{padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px;}.edn-article-list-row > div{padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px;}.edn-article-list-row > div{padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px;}.edn-article-list-row > div{padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px;}.edn-article-list-row > div{padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px;}.edn-article-list-row > div{padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px;}}</style><link rel='SHORTCUT ICON' href='/Portals/0/favicon.ico?ver=_3VGTHkgAVIUwh1Qii2xGw%3d%3d' type='image/x-icon' /><meta name="eds__GmapsInitData" content="{&quot;instanceGlobal&quot;:&quot;EasyDnnSolutions1_1_instance&quot;,&quot;google&quot;:{&quot;maps&quot;:{&quot;api&quot;:{&quot;key&quot;:&quot;&quot;,&quot;libraries&quot;:[&quot;geometry&quot;,&quot;places&quot;]}}}}" />

**Comment by meetmandeep** [comment]
Thanks for reporting this. We've identified the issue and it will be resolved in RC.

**Comment by Tychodewaard** [comment]
I found a way to delete the styles from the database. But everytime I hit the publish button, the styles are back. As it is driving me insane : is there a way to really delete it somewhere? Please, please pretty please?

**Comment by meetmandeep** [comment]
In the database (vj_core_pages), you will find a CSS and styleJSON column. It seems like you only removed the style from CSS column and not from styleJSON which will re add them every time you publish the page. 

This issue has been resolved in RC as we no longer allow creating custom block with your own HTML/CSS. Use Custom Code block instead for that purpose.
