### ISSUE TITLE
Module Actions not working correctly

### ISSUE THREAD

**Issue by leedavi** [vanjarosoftware/Vanjaro.Platform#856]
public ModuleActionCollection ModuleActions
        {
            get
            {
                var actions = new ModuleActionCollection();
                    var adminurl = "/DesktopModules/ModuleStuff/admin.html?moduleid=[moduleid]&tabid=[tabid]&systemkey=[systemkey]";
                    adminurl = adminurl.ToLower().Replace("[moduleid]", ModuleId.ToString());
                    adminurl = adminurl.ToLower().Replace("[tabid]", TabId.ToString());
                    adminurl = adminurl.ToLower().Replace("[systemkey]",  _systemkey);
                    actions.Add(GetNextActionID(), "Setting", "", "", "icon_dashboard_16px.gif", adminurl, false, SecurityAccessLevel.Edit, true, false);
                return actions;
            }
        }

Does not work, The menu is there, but the link goes to a blankpage.

**Comment by meetmandeep** [comment]
Can you provide additional information? Which module were you using? 

Please provide step by step instructions to duplicate the issue. Thanks

**Comment by leedavi** [comment]
I was using a bespoke closed source module, that was created for a client and  works on DNN without any issue.

The code I provided is "near" identical.

The module action renders a simple html link to a html file in the same site.  I think if you test that code in any  module, you'll find it does not work.
