### ISSUE TITLE
Add the ability to add a CSS stylesheet to be included in the CSS bundling  

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#862]
Maybe a setting in Integrations and connectors for an external style sheet to be included in the page builds. This way custom CSS can be included and kept away from prying. I know why the individual CSS settings were removed from blocks. For those of us that have been working with bootstrap we all know how to override Bootstrap with a site specific CSS. And if were good we NEVER change bootstrap source> :-)

**Comment by meetmandeep** [comment]
There are several ways to include your CSS and have it bundled along with other CSS files:

1. Use Custom CSS from Menu > Design (This is same as DNN Portal.css)
2. Use Menu > Design > Theme Builder > Custom to write your own sass or css directly which would be bundled in the theme.css
