### ISSUE TITLE
Vanjaro Menu still functional after the site has timed out and login is expired. 

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#863]

**Comment by meetmandeep** [comment]
The menu is rendered and maintained on the page (client side). You may see that the menu is functional (such as the site link showing Roles/Users and so on) but clicking on any of the application links would result in "you are not authorized to view this page" error. 

In other words, you may navigate to Site but you wouldn't be able to interact or view any of the data (for example, you would get an error if you click on Users or Roles or Settings and so forth)
