### ISSUE TITLE
Can't use Apps

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#871]
I installed the Vanjaro for DNN extension on a clean DNN 9.9.0 environment.
1) Create a new page
2) Drag an HTML App to the page.
3) Click the hamburger menu and select Edit Content.

Nothing happens.
In the developer console, I see this:
 Uncaught SyntaxError: Invalid left-hand side in assignment
    at HTMLDivElement.<anonymous> (uxmanager.min.js?cdv=2:1075)
(anonymous) @ uxmanager.min.js?cdv=2:1075

**Comment by X3Technology** [comment]
Same happens with the DDR Menu app, so I assume this is a global App issue

**Comment by X3Technology** [comment]
I next tried a clean "Vanjaro Platform" install package and then installed the HTML module extension from the DNN990 distribution.  Now, when I drag the HTML App to the page, everything seems to work just fine.  So it must be a problem specific to either the "Vanjaro as an extension" installation or perhaps the DNN990 base environment?

**Comment by meetmandeep** [comment]
We'll check this on a clean DNN 9.9 w/Vanjaro for DNN Extensions. 

Just curious, why use the HTML Module. It defeats the purpose of using Vanjaro. Same with DDR Menu. You have the Menu Block that does everything DDR Menu does without fiddling with any code or config.

**Comment by X3Technology** [comment]
It wasn’t so much that I wanted to use those particular modules.  It’s just those were the ones immediately available with a clean DNN 990 installation.  I wouldn’t actually use HTML module over the Vanjaro HTML block or the DDR Menu module over the Menu block.  I was just testing to see if Apps would work.

**Comment by meetmandeep** [comment]
I now understand why the label disappears. If you're working with a small block such as an icon then there's isn't enough real estate to show the label and action icons such as (copy / delete). Therefore, the design team is hiding the label when try to interact with these icons. 

We'll have the design team make the final call but I agree that we need visibility into the selected block.

**Comment by mathisjay** [comment]
I think the above comment was for #872.

**Comment by meetmandeep** [comment]
Yes. Reposting there.
