### ISSUE TITLE
Sidebar designer should show the type of the currently selected html element.

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#872]
As you move the cursor around the page, there is a clear popup label in the upper left of the hovered element.  For xeample, hovering over the grid on the default page.
![with hover](https://user-images.githubusercontent.com/1585717/109715479-b0a42380-7b71-11eb-85bf-b7e68154af03.PNG)

Clicking on the grid element will correctly change the sidebar designer to reflect the options available for the currently selected element.

However, once the cursor is no longer hovering over the grid, the "Grid" label disappears and the designer does not indicate what kind of element these options are for:
![without hover](https://user-images.githubusercontent.com/1585717/109715491-b39f1400-7b71-11eb-80ef-92762470f583.PNG)

Note: if you switch the Styling tab, there is some muted text that provides some context, but it should be shown on both the Options tab and the Styling tab.

![styling tab](https://user-images.githubusercontent.com/1585717/109716042-4cce2a80-7b72-11eb-8a9c-1426926655fd.PNG)

I suggest simply putting the name of the element type on the designer so it is clear what the shown options are for:
![options tab](https://user-images.githubusercontent.com/1585717/109716416-db42ac00-7b72-11eb-9636-5454f77be3c0.png)

**Comment by meetmandeep** [comment]
>However, once the cursor is no longer hovering over the grid, the "Grid" label disappears and the designer does not indicate what >kind of element these options are for:

I suppose we can easily solve this by always showing the "Grid" label of the selected element. In that case, is it necessary to also show a label in the options window?

**Comment by X3Technology** [comment]
In my opinion, it would be more clear to show the label in the outline of the element AND in the options window.  The label is already being shown in the Styling tab so it feels weird that it is not also in the Options tab.

**Comment by X3Technology** [comment]
Re: https://github.com/vanjarosoftware/Vanjaro.Platform/issues/871#issuecomment-789259679

I see your point about the label and the actions being visible at the same time for small elements like an icon.  

Here is one idea:
Currently, the text label shows up on the top left (only when hovered) and the action icons show up top right (only when clicked).
What if you replaced the text label with an icon label (solves for translation troubles too!).  Then, when the element is clicked on, simply append the action icons to the label icon (all flowing from the left).

**Comment by meetmandeep** [comment]
Thanks for the suggestion @mathisjay but showing an icon would not be sufficient as there are dozens of blocks (nested such Column within a Grid). You can also create your own blocks. We'll have the design team figure this out. I think just adding the label to the Options would be sufficient.
