### ISSUE TITLE
Apps don't refresh content when their edit screen is closed.

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#875]
1) Drag an HTML app to the page
2) Edit some content, then click Save

The page will not reflect the content change until the page is reloaded.  The user will expect to see this change immediately.  

Is there a way to refresh just that module content?  Or force a page refresh when an App's edit UX closes?

**Comment by meetmandeep** [comment]
I believe there are some issues with HTML Module; I've tested this with other modules and the content refreshes. 

Thanks for reporting this. We'll investigate.
