### ISSUE TITLE
Button Designer Styles

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#876]
This is a minor UX nit-pick but it gave me pause when I first looked at it.

In a regular Text block designer, the Styles section looks like this:
![text_styles](https://user-images.githubusercontent.com/1585717/109725785-a8eb7b80-7b7f-11eb-952d-4b1048e35822.PNG)
This is great and clearly shows the various predefined CSS effects that can be applied to the selected Text block.

However, in the Button block designer, in the Styles section, the samples actually look like real buttons:
![Button_styles](https://user-images.githubusercontent.com/1585717/109726008-fa940600-7b7f-11eb-81e5-68d1bd5ef30b.PNG)

When I first looked at this, it made me think that this was going to be a real-time designer that would show all my other choices for things like fore color, background color, size, etc.  But the page already does that in place.  So, to me, it was slightly confusing and I thought it was broken.  If the Styles section is meant to simply show the various predefined CSS effects available, then I think it would be clearer that the samples not be rendered to look like a button that may or may not (probably not) match the selected button.  Just show the CSS effect differences like the regular Text block designer does.

As I said, I know this is nit-picky...

**Comment by X3Technology** [comment]
Alternatively, perhaps it was intended that the Styles section would also include some pre-defined CSS options that go beyond just the text styling to include actual "button" things like border-radius, border-color or padding, etc, in which case it makes sense for the samples to look like an actual button.

**Comment by meetmandeep** [comment]
Yes. That's precisely the case. Your predefined buttons could have rounder corners or drop shadows and so forth.

**Comment by X3Technology** [comment]
Fantastic!  I assume there is some way for a designer to add custom pre-defined CSS options so they show up in the Styles section?

**Comment by meetmandeep** [comment]
Absolutely! Menu > Design > Themes > Settings > Site > Styles: Button 

Each style corresponds to an autogenerated class such as .button-style-1

You may add your own Custom CSS from:

- Menu > Design > Custom CSS
- Menu > Design > Themes > Settings > Custom

**Comment by X3Technology** [comment]
Amazing! Wow, you guys thought of everything!
