### ISSUE TITLE
How to implement custom javascript in theme

### ISSUE THREAD

**Issue by X3Technology** [vanjarosoftware/Vanjaro.Platform#877]
I would like to add some custom javascript that detects scroll position so that I can toggle a CSS class on the header nav to flip from a dark theme to a light theme.

Something like this:
https://themes.getbootstrap.com/preview/?theme_id=3569

Is that possible?

**Comment by meetmandeep** [comment]
You can always add your own custom JS to the theme. 

Create a new file named theme.js and place it in the theme folder: /Portals/_Default/vThemes/Basic/

Vanjaro will automatically include and bundle this JS.

**Comment by X3Technology** [comment]
nice!

**Comment by X3Technology** [comment]
It would be a "nice to have" to be able to edit the theme.js file directly from within the UX.
