### ISSUE TITLE
DNN modules do not display custom tabs

### ISSUE THREAD

**Issue by turbz214** [vanjarosoftware/Vanjaro.Platform#887]
![image](https://user-images.githubusercontent.com/17383316/109848584-6f1d8200-7c1e-11eb-84f5-2322a8e0fbd8.png)

**Comment by turbz214** [comment]
Hello, is there a planned released date for this fix?

**Comment by meetmandeep** [comment]
@turbz214 This should be part of Release Candidate 2; hopefully in 2 weeks.
