### ISSUE TITLE
List Item Block: Can't edit text after adding link

### ISSUE THREAD

**Issue by joshgk00** [vanjarosoftware/Vanjaro.Platform#888]
After adding a List Item block to a page, and making a List Item a link, you can no longer edit the text.

Steps to reproduce:
1. Create a page
2. Add a List Block
3. Select the text from the first list item and make it a link
4. Set the link to a file in the site root
5. Try to double click to change the text.

Expected Behavior:
I'd expect that one would be able to edit the text after making it a link. 

Actual Behavior: Double clicking the link, has no affect. You are not able to edit the text of the link in the List Item

Screencast:
https://www.screencast.com/t/TVM0OC74pP

**Comment by X3Technology** [comment]
I think the problem goes beyond just the List block.  
If you play with the default template on a clean install, there is a Heading block "Welcome to Vanjaro" where "Vanjaro" is hyperlinked.  You can't edit that text either.  At least not by directly clicking on "Vanjaro".  You have to double-click somewhere else on the "Welcome to" text and THEN click on the "Vanjaro" part.

**Comment by eswanzey** [comment]
Please note that if a portion of a list item is "bolded," css styling is applied that breaks the line of text.

Also note that a selection of text within a list item can't be styled such as changing the color.
