### ISSUE TITLE
Inconsistency button font size

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#910]
When you select a button, you can give it a font size in px or em.
If you go to the styling tab, you can give the button a font size in vw (and some other options). 

It is a bit confusing if you later return and have the default options show the vw value and see px selected.

Solution is to offer vw (and possible other options) in the options tab to apply the font size.
![image](https://user-images.githubusercontent.com/9091997/110324916-e84e1800-8016-11eb-97de-084ddff58288.png)
![image](https://user-images.githubusercontent.com/9091997/110324949-f865f780-8016-11eb-973d-8c77e1e20bf1.png)

**Comment by meetmandeep** [comment]
> If you go to the styling tab, you can give the button a font size in vw (and some other options).

You can specify a font-size in px or vw in both Options and Styling

> It is a bit confusing if you later return and have the default options show the vw value and see px selected.

I was unable to duplicate this. I do see vw selected in options if I set vw from Styling Tab. 

I do see an issue if I were to set em or any of the other options other than vw and px.
