### ISSUE TITLE
Style text not saved

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#911]
I have added Montserrat as a custom font.
If I go to design and want to appoint Montserrat as default font for text (style a), this is not saved.

**Comment by meetmandeep** [comment]
I'm unable to duplicate this. Can you try again? Be sure to save the changes after updating style a.

**Comment by Tychodewaard** [comment]
I tried again last night and then it worked. Actually did the same so, not sure... But let's close this one :-)
