### ISSUE TITLE
Add options to button design

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#912]
In order to have an easy consistency in layout it would be great to have some options addded to the buttons.
- Font-size
- Font color
- Background color
- Paddding (left, right, top, bottom)

This way you can translate a design system to the theme.

![image](https://user-images.githubusercontent.com/9091997/110325900-3a436d80-8018-11eb-88b0-9191f1be0cee.png)

**Comment by meetmandeep** [comment]
Font-Size & Font-Color are not part of the styles since they can be easily changed from option. But I agree that background color, border color, border-radius, and padding can be added.
