### ISSUE TITLE
Choose button style

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#914]
I have applied some button styles in the theme designer.
But if I drop a button to a page, I can not select a defined style.

**Comment by meetmandeep** [comment]
I'm not sure if I understand the issue. Can you provide a screenshot, screencast, or elaborate? Thanks

**Comment by Tychodewaard** [comment]
It works like it should. The CSS inspector was picking up the wrong element.
