### ISSUE TITLE
Can not delete custom part

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#918]
Themes-Basic-Settings-Custom.
Accidenntally I saved a piece of css without giving it a title. Trying to clean up, I find that I can not delete it.

![image](https://user-images.githubusercontent.com/9091997/110452324-5e10bd00-80c5-11eb-8121-b5aebe5d4593.png)
![image](https://user-images.githubusercontent.com/9091997/110452688-b21ba180-80c5-11eb-80ae-4107e2bce52c.png)

1. Is this a bug?
2. Is there a way to delete this somewhere? File/Database?

**Comment by meetmandeep** [comment]
> Accidenntally I saved a piece of css without giving it a title. Trying to clean up, I find that I can not delete it.

How did you do it? I couldn't find a way to save without providing a title. 

> Is there a way to delete this somewhere? File/Database?

Custom Theme options are saved in theme.json file at /Portals/PortalID/vThemes/ThemeName/editor/be134fd2-3a3d-4460-8ee9-2953722a5ab2/
