### ISSUE TITLE
Issue with multiple menu blocks on same page

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#928]
When there's more than one menu block on a page, changing settings for one menu block changes the settings for other menu blocks on the same page.

**Comment by meetmandeep** [comment]
Did you select "Customize This Block Only"? 

![image](https://user-images.githubusercontent.com/29958123/110536971-ecda0580-80d6-11eb-9693-87cf207cc6f3.png)

**Comment by eswanzey** [comment]
Oh yeah, nice. You referred to this feature in a posted video, suggesting it would be the topic of a future video but I don't think it's available yet.
