### ISSUE TITLE
Custom Code blocks not visible in editor mode

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#931]
The only way to find any Custom Code blocks is via the Navigator because they aren't visible to be manually selected. While it's nice that they disappear and not impact the visual layout, I don't look forward to working with a page that someone else put together and having to use the Navigator to find all instances of any Code blocks.

**Comment by meetmandeep** [comment]
I'm not sure if I understand the issue. Can you elaborate. You can tell if you're working with a Code Block by looking at the options. See: 
![image](https://user-images.githubusercontent.com/29958123/110535506-388baf80-80d5-11eb-8c49-c9191d9ca09c.png)

**Comment by eswanzey** [comment]
Unable to re-create the issue so closing this out.
