### ISSUE TITLE
Module header/footer uneditable through edit interface

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#932]
Vanjaro displays the contents of any module header or footer, but those areas aren't exposed through the editor interface and can't be revised through the interface.

**Comment by meetmandeep** [comment]
Vanjaro will not support Header/Footer concept on Modules/Apps. It's super easy to add a header/footer to an app by dragging the necessary blocks. 

DNN itself does not recommend using header/footer anymore as it flags any modules using these in Security Analyzer.
