### ISSUE TITLE
Menu block submenu flyout on right wide

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#933]
When a menu is right-aligned, it shows this issue clearly whereby submenus near the right edge of the browser window fly out beyond the right edge boundary of the browser window.

**Comment by meetmandeep** [comment]
Thanks for reporting this. I'm adding a screenshot to illustrate. 
![image](https://user-images.githubusercontent.com/29958123/110535121-ba2f0d80-80d4-11eb-9898-475fc6324cf3.png)
