### ISSUE TITLE
Menu block disappearing when moved to a global block. MAJOR ISSUE

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#941]
https://user-images.githubusercontent.com/6786299/110551334-ebbacf80-80fa-11eb-9c3d-23dde1ffc128.mp4

**Comment by scottw12** [comment]
Page displays with a div with the word menu....And no java errors or page errors.

```
<div id="dnn_ContentPane">
<div class="vj-wrapper">
<div id="vjEditor">
<div data-guid="1cd843fd-c99b-4415-956e-204540cec02d" id="i4qd">
<section class="vj-section" id="iqtg">
				<div class="align-ib" id="i0gi">Menu</div>
</section>
</div>
</div>
</div>
</div>
```

**Comment by meetmandeep** [comment]
I'm able to duplicate this. Thanks for reporting @scottw12

**Comment by mksmanish79** [comment]
@scottw12 Add a grid inside section and move the menu inside it will fix the issue. We will also fix this in upcoming release.

**Comment by Tychodewaard** [comment]
Do you have a workaround if there is already a section and grid?
https://www.youtube.com/watch?v=TENaYhEqdBE 
(14 seconds short video)
