### ISSUE TITLE
Global blocks not visible after upgrade 

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#947]
Just upgraded beta to RC. 
And the menu has disappeared. Well, if you are not logged in.

If you are logged in, you can see the block/section but there is no wat to make it visible. 
Permissions are set 'same as page'

Don't know if it is an upgrade thing or if it helps tackling something else.

**Comment by meetmandeep** [comment]
This was marked as a Breaking Change in RC notes: https://github.com/vanjarosoftware/Vanjaro.Platform/releases/tag/v1.0.4

All Global Blocks will be removed. Please refer to mitigation steps.
