### ISSUE TITLE
Adding a custom font breaks colours 

### ISSUE THREAD

**Issue by Tychodewaard** [vanjarosoftware/Vanjaro.Platform#971]
**Describe the bug**
I had assigned colours to the theme. After adding Open sans the assigned colours are not set anymore and there seems to be a random set of colours. At least it is not the default set.

**Screenshots**
I created a desktop recording : https://www.youtube.com/watch?v=DLfGGl7tYuk

**Additional context**
It is a multiportal setup. The colours in the other portals are not impacted.

**Comment by Tychodewaard** [comment]
I updated the video link as I discovered that there is more broken than initially detected.

**Comment by meetmandeep** [comment]
@Tychodewaard the video demonstrates the issue; but does not explain the steps you took to get there. Can you provide step by step instructions on how you added "Open Sans" and if there is anything else you did other than adding them to Style A of Text and Heading.

**Comment by Tychodewaard** [comment]
I added the font as shown in the video 'custom fonts'. I can not really show you how it looks in the 'custom' part as that UI is broken as well:
![image](https://user-images.githubusercontent.com/9091997/111755975-fc590b80-8899-11eb-911e-32ae32b20ab4.png)

I did nothing else besides appointing styles for text and header.

**Comment by Gaganbird** [comment]
I have a couple of questions:

- Are you on RC?
- Have you added a link tag or link content in the custom font?

1. Try Save button (Themes > Basic > Site/Custom > Save)
2. Try "Clear Client Cache" and "Restart Application"

**Comment by Tychodewaard** [comment]
Yes, I am on RC.
I used the @import for the font, not the link.
I have saved the theme, cleared the cache and restarted the application.

**Comment by Gaganbird** [comment]
I was unable to duplicate the issues on my test server. Please repeat the steps on a clean RC and provide a screencast.
