### ISSUE TITLE
Missing CUSTOM BLOCK when I press the "+" button.  I see PAGE, USER, ROLE, UPLOAD FILE, (but missing CUSTOM BLOCK).   

### ISSUE THREAD

**Issue by jfre11** [vanjarosoftware/Vanjaro.Platform#974]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Current behavior**
A clear and concise description of what is currently happening.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jfre11** [comment]
![Capture](https://user-images.githubusercontent.com/22160542/111691645-c2313080-87eb-11eb-9aff-59dedc244b58.JPG)

Im using Vanjaro Platform 1.0.4 (RC)
DNN Platform 09.09.00 
on localhost

**Comment by Tychodewaard** [comment]
As the custom blocks have been removed, I assumed that this has been deprecated. You can utilize the custom code blocks instead. For css and js, you can either include that using <style> and <script> or put the css in portal.css (in Vanjaro 'custom styling') and the js in the theme.js
If you don't want customers to use this, you can save the block as a custom block which will make m appear there.

Hope this helps.

**Comment by meetmandeep** [comment]
That's correct. The ability to create custom blocks from your own html/css has been removed. You can always create custom blocks by using the Editor. Simply add any blocks you want in a Section and use the Section > Save as custom block option. 

As @Tychodewaard  pointed out, you can use your own custom html/css in a Custom Code Block

**Comment by jfre11** [comment]
Thanks Mandeep,  

You might want to  take down your video on custom blocks.   BTW.. I really love Vanjaro – great job!!  I’m in the process of revamping all my old websites using Vanjaro.

**Comment by meetmandeep** [comment]
Yes. We'll release new videos along with the official Vanjaro Release; at that time, we'll take all the preview videos down.
