### ISSUE TITLE
Enabling Google Recaptcha connector prevents login

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#979]
**Describe the bug**
With the Google Recaptcha site key and secret key set and enabled, I am no longer able to login to the site.

**To Reproduce**
1. Enter site key and secret key in Vanjaro's Google Analytics connector
2. Enable the connector
2. Logout
3. Try to login to the site

**Expected behavior**
I should be able to login.

**Workaround**
Set Vanjaro.Integration.Captcha.Enabled to False in PortalSettings table to restore login ability

**Current behavior**
100% failure on repeated login attempts. The on-screen response with each failed attempt is "We couldn't determine if you're human or robot. Please try again."

**Additional context**
Stack Trace:
AbsoluteURL /API/Login/Login/UserLogin DefaultDataProvider DotNetNuke
AbsoluteURL:/API/Login/Login/UserLogin
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:26b025cf-11e1-4f24-8111-0d4e0ba61589
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:gW4BhnnLHtk9BZ1RgvrOBa2xrBE=
Message:Object reference not set to an instance of an object.
StackTrace:
at Vanjaro.Core.Services.Captcha.Validate(String action, String token, Decimal minimumScore)

**Comment by meetmandeep** [comment]
@eswanzey Can you confirm if you're using v3 Site & Secret Key?

**Comment by eswanzey** [comment]
Was v2; v3 works as expected.

----------------------------------------
