### ISSUE TITLE
Live-Forms can't add new condition when action = on form submission 

### ISSUE THREAD

**Issue by eswanzey** [vanjarosoftware/Vanjaro.Platform#987]
**Describe the bug**
Unable to add a new condition to an "On Form Submission" action

**To Reproduce**
1. Edit a form and open Options / Actions / On Form Submission and create an action
2.Try to add a new condition to the action, it won't

I know that you indicated "Vanjaro is getting its own version of Live Forms that is integrated with Vanjaro and provides a native UX. It will retain all features of Live Forms and will address all UX issues." so maybe is moot in that respect.

**Comment by meetmandeep** [comment]
@eswanzey Yes. Form Builder (Live Forms for Vanjaro) will be available with official Vanjaro Release. It features a native UX within Vanjaro and should be available for community preview next week.
